// Code generated by protoc-gen-go.
// source: syndicate_api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	syndicate_api.proto

It has these top-level messages:
	RingMsg
	StoreResult
	StatusRequest
	StatusMsg
	EmptyMsg
	RingStatus
	Node
	ModifyMsg
	RingConf
	Conf
	RegisterRequest
	HardwareProfile
	Disk
	NodeConfig
	Ring
	SearchResult
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type RingMsg struct {
	Version  int64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ring     []byte `protobuf:"bytes,2,opt,name=ring,proto3" json:"ring,omitempty"`
	Builder  []byte `protobuf:"bytes,3,opt,name=builder,proto3" json:"builder,omitempty"`
	Deadline int64  `protobuf:"varint,4,opt,name=deadline" json:"deadline,omitempty"`
	Rollback int64  `protobuf:"varint,5,opt,name=rollback" json:"rollback,omitempty"`
}

func (m *RingMsg) Reset()                    { *m = RingMsg{} }
func (m *RingMsg) String() string            { return proto1.CompactTextString(m) }
func (*RingMsg) ProtoMessage()               {}
func (*RingMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StoreResult struct {
	Version int64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ring    bool   `protobuf:"varint,2,opt,name=ring" json:"ring,omitempty"`
	Builder bool   `protobuf:"varint,3,opt,name=builder" json:"builder,omitempty"`
	ErrMsg  string `protobuf:"bytes,4,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
}

func (m *StoreResult) Reset()                    { *m = StoreResult{} }
func (m *StoreResult) String() string            { return proto1.CompactTextString(m) }
func (*StoreResult) ProtoMessage()               {}
func (*StoreResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StatusRequest struct {
	Ring    bool `protobuf:"varint,1,opt,name=ring" json:"ring,omitempty"`
	Builder bool `protobuf:"varint,2,opt,name=builder" json:"builder,omitempty"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto1.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StatusMsg struct {
	Version      int64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ringstats    string `protobuf:"bytes,2,opt,name=ringstats" json:"ringstats,omitempty"`
	Builderstats string `protobuf:"bytes,3,opt,name=builderstats" json:"builderstats,omitempty"`
	Master       string `protobuf:"bytes,4,opt,name=master" json:"master,omitempty"`
}

func (m *StatusMsg) Reset()                    { *m = StatusMsg{} }
func (m *StatusMsg) String() string            { return proto1.CompactTextString(m) }
func (*StatusMsg) ProtoMessage()               {}
func (*StatusMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto1.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RingStatus struct {
	Status  bool  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Version int64 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *RingStatus) Reset()                    { *m = RingStatus{} }
func (m *RingStatus) String() string            { return proto1.CompactTextString(m) }
func (*RingStatus) ProtoMessage()               {}
func (*RingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Node struct {
	Id        uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Active    bool     `protobuf:"varint,2,opt,name=active" json:"active,omitempty"`
	Capacity  uint32   `protobuf:"varint,3,opt,name=capacity" json:"capacity,omitempty"`
	Tiers     []string `protobuf:"bytes,4,rep,name=tiers" json:"tiers,omitempty"`
	Addresses []string `protobuf:"bytes,5,rep,name=addresses" json:"addresses,omitempty"`
	Meta      string   `protobuf:"bytes,6,opt,name=meta" json:"meta,omitempty"`
	Conf      []byte   `protobuf:"bytes,7,opt,name=conf,proto3" json:"conf,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto1.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ModifyMsg struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Id    uint64 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

func (m *ModifyMsg) Reset()                    { *m = ModifyMsg{} }
func (m *ModifyMsg) String() string            { return proto1.CompactTextString(m) }
func (*ModifyMsg) ProtoMessage()               {}
func (*ModifyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RingConf struct {
	Status *RingStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Conf   *Conf       `protobuf:"bytes,2,opt,name=conf" json:"conf,omitempty"`
}

func (m *RingConf) Reset()                    { *m = RingConf{} }
func (m *RingConf) String() string            { return proto1.CompactTextString(m) }
func (*RingConf) ProtoMessage()               {}
func (*RingConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RingConf) GetStatus() *RingStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RingConf) GetConf() *Conf {
	if m != nil {
		return m.Conf
	}
	return nil
}

type Conf struct {
	Conf            []byte `protobuf:"bytes,1,opt,name=conf,proto3" json:"conf,omitempty"`
	RestartRequired bool   `protobuf:"varint,2,opt,name=restartRequired" json:"restartRequired,omitempty"`
}

func (m *Conf) Reset()                    { *m = Conf{} }
func (m *Conf) String() string            { return proto1.CompactTextString(m) }
func (*Conf) ProtoMessage()               {}
func (*Conf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type RegisterRequest struct {
	Hostname string           `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Addrs    []string         `protobuf:"bytes,2,rep,name=addrs" json:"addrs,omitempty"`
	Tiers    []string         `protobuf:"bytes,3,rep,name=tiers" json:"tiers,omitempty"`
	Hardware *HardwareProfile `protobuf:"bytes,4,opt,name=hardware" json:"hardware,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto1.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RegisterRequest) GetHardware() *HardwareProfile {
	if m != nil {
		return m.Hardware
	}
	return nil
}

type HardwareProfile struct {
	Memtotal uint64  `protobuf:"varint,1,opt,name=memtotal" json:"memtotal,omitempty"`
	Memfree  uint64  `protobuf:"varint,2,opt,name=memfree" json:"memfree,omitempty"`
	Cpus     int64   `protobuf:"varint,3,opt,name=cpus" json:"cpus,omitempty"`
	Disks    []*Disk `protobuf:"bytes,4,rep,name=disks" json:"disks,omitempty"`
}

func (m *HardwareProfile) Reset()                    { *m = HardwareProfile{} }
func (m *HardwareProfile) String() string            { return proto1.CompactTextString(m) }
func (*HardwareProfile) ProtoMessage()               {}
func (*HardwareProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *HardwareProfile) GetDisks() []*Disk {
	if m != nil {
		return m.Disks
	}
	return nil
}

type Disk struct {
	Device string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Size   uint64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Used   uint64 `protobuf:"varint,4,opt,name=used" json:"used,omitempty"`
}

func (m *Disk) Reset()                    { *m = Disk{} }
func (m *Disk) String() string            { return proto1.CompactTextString(m) }
func (*Disk) ProtoMessage()               {}
func (*Disk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type NodeConfig struct {
	Localid uint64 `protobuf:"varint,1,opt,name=localid" json:"localid,omitempty"`
	Ring    []byte `protobuf:"bytes,2,opt,name=ring,proto3" json:"ring,omitempty"`
}

func (m *NodeConfig) Reset()                    { *m = NodeConfig{} }
func (m *NodeConfig) String() string            { return proto1.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()               {}
func (*NodeConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type Ring struct {
	Version int64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ring    []byte `protobuf:"bytes,2,opt,name=ring,proto3" json:"ring,omitempty"`
}

func (m *Ring) Reset()                    { *m = Ring{} }
func (m *Ring) String() string            { return proto1.CompactTextString(m) }
func (*Ring) ProtoMessage()               {}
func (*Ring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SearchResult struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *SearchResult) Reset()                    { *m = SearchResult{} }
func (m *SearchResult) String() string            { return proto1.CompactTextString(m) }
func (*SearchResult) ProtoMessage()               {}
func (*SearchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SearchResult) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto1.RegisterType((*RingMsg)(nil), "proto.RingMsg")
	proto1.RegisterType((*StoreResult)(nil), "proto.StoreResult")
	proto1.RegisterType((*StatusRequest)(nil), "proto.StatusRequest")
	proto1.RegisterType((*StatusMsg)(nil), "proto.StatusMsg")
	proto1.RegisterType((*EmptyMsg)(nil), "proto.EmptyMsg")
	proto1.RegisterType((*RingStatus)(nil), "proto.RingStatus")
	proto1.RegisterType((*Node)(nil), "proto.Node")
	proto1.RegisterType((*ModifyMsg)(nil), "proto.ModifyMsg")
	proto1.RegisterType((*RingConf)(nil), "proto.RingConf")
	proto1.RegisterType((*Conf)(nil), "proto.Conf")
	proto1.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto1.RegisterType((*HardwareProfile)(nil), "proto.HardwareProfile")
	proto1.RegisterType((*Disk)(nil), "proto.Disk")
	proto1.RegisterType((*NodeConfig)(nil), "proto.NodeConfig")
	proto1.RegisterType((*Ring)(nil), "proto.Ring")
	proto1.RegisterType((*SearchResult)(nil), "proto.SearchResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for RingDist service

type RingDistClient interface {
	Store(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error)
	Revert(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusMsg, error)
	Setup(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error)
}

type ringDistClient struct {
	cc *grpc.ClientConn
}

func NewRingDistClient(cc *grpc.ClientConn) RingDistClient {
	return &ringDistClient{cc}
}

func (c *ringDistClient) Store(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error) {
	out := new(StoreResult)
	err := grpc.Invoke(ctx, "/proto.RingDist/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ringDistClient) Revert(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error) {
	out := new(StoreResult)
	err := grpc.Invoke(ctx, "/proto.RingDist/Revert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ringDistClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/proto.RingDist/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ringDistClient) Setup(ctx context.Context, in *RingMsg, opts ...grpc.CallOption) (*StoreResult, error) {
	out := new(StoreResult)
	err := grpc.Invoke(ctx, "/proto.RingDist/Setup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RingDist service

type RingDistServer interface {
	Store(context.Context, *RingMsg) (*StoreResult, error)
	Revert(context.Context, *RingMsg) (*StoreResult, error)
	Status(context.Context, *StatusRequest) (*StatusMsg, error)
	Setup(context.Context, *RingMsg) (*StoreResult, error)
}

func RegisterRingDistServer(s *grpc.Server, srv RingDistServer) {
	s.RegisterService(&_RingDist_serviceDesc, srv)
}

func _RingDist_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RingDistServer).Store(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RingDist_Revert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RingDistServer).Revert(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RingDist_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RingDistServer).Status(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RingDist_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RingDistServer).Setup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _RingDist_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RingDist",
	HandlerType: (*RingDistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _RingDist_Store_Handler,
		},
		{
			MethodName: "Revert",
			Handler:    _RingDist_Revert_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RingDist_Status_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _RingDist_Setup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for Syndicate service

type SyndicateClient interface {
	AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	ModNode(ctx context.Context, in *ModifyMsg, opts ...grpc.CallOption) (*RingStatus, error)
	SetConf(ctx context.Context, in *Conf, opts ...grpc.CallOption) (*RingStatus, error)
	SetActive(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	SetCapacity(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	ReplaceAddresses(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	ReplaceTiers(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error)
	GetVersion(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*RingStatus, error)
	GetGlobalConfig(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*RingConf, error)
	GetNodeConfig(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingConf, error)
	SearchNodes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*SearchResult, error)
	GetRing(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*Ring, error)
	RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*NodeConfig, error)
}

type syndicateClient struct {
	cc *grpc.ClientConn
}

func NewSyndicateClient(cc *grpc.ClientConn) SyndicateClient {
	return &syndicateClient{cc}
}

func (c *syndicateClient) AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/AddNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/RemoveNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) ModNode(ctx context.Context, in *ModifyMsg, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/ModNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) SetConf(ctx context.Context, in *Conf, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/SetConf", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) SetActive(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/SetActive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) SetCapacity(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/SetCapacity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) ReplaceAddresses(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/ReplaceAddresses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) ReplaceTiers(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/ReplaceTiers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) GetVersion(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*RingStatus, error) {
	out := new(RingStatus)
	err := grpc.Invoke(ctx, "/proto.Syndicate/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) GetGlobalConfig(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*RingConf, error) {
	out := new(RingConf)
	err := grpc.Invoke(ctx, "/proto.Syndicate/GetGlobalConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) GetNodeConfig(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RingConf, error) {
	out := new(RingConf)
	err := grpc.Invoke(ctx, "/proto.Syndicate/GetNodeConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) SearchNodes(ctx context.Context, in *Node, opts ...grpc.CallOption) (*SearchResult, error) {
	out := new(SearchResult)
	err := grpc.Invoke(ctx, "/proto.Syndicate/SearchNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) GetRing(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*Ring, error) {
	out := new(Ring)
	err := grpc.Invoke(ctx, "/proto.Syndicate/GetRing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syndicateClient) RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*NodeConfig, error) {
	out := new(NodeConfig)
	err := grpc.Invoke(ctx, "/proto.Syndicate/RegisterNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Syndicate service

type SyndicateServer interface {
	AddNode(context.Context, *Node) (*RingStatus, error)
	RemoveNode(context.Context, *Node) (*RingStatus, error)
	ModNode(context.Context, *ModifyMsg) (*RingStatus, error)
	SetConf(context.Context, *Conf) (*RingStatus, error)
	SetActive(context.Context, *Node) (*RingStatus, error)
	SetCapacity(context.Context, *Node) (*RingStatus, error)
	ReplaceAddresses(context.Context, *Node) (*RingStatus, error)
	ReplaceTiers(context.Context, *Node) (*RingStatus, error)
	GetVersion(context.Context, *EmptyMsg) (*RingStatus, error)
	GetGlobalConfig(context.Context, *EmptyMsg) (*RingConf, error)
	GetNodeConfig(context.Context, *Node) (*RingConf, error)
	SearchNodes(context.Context, *Node) (*SearchResult, error)
	GetRing(context.Context, *EmptyMsg) (*Ring, error)
	RegisterNode(context.Context, *RegisterRequest) (*NodeConfig, error)
}

func RegisterSyndicateServer(s *grpc.Server, srv SyndicateServer) {
	s.RegisterService(&_Syndicate_serviceDesc, srv)
}

func _Syndicate_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).AddNode(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).RemoveNode(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_ModNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ModifyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).ModNode(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_SetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Conf)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).SetConf(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_SetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).SetActive(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_SetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).SetCapacity(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_ReplaceAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).ReplaceAddresses(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_ReplaceTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).ReplaceTiers(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).GetVersion(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_GetGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).GetGlobalConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_GetNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).GetNodeConfig(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).SearchNodes(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_GetRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).GetRing(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Syndicate_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SyndicateServer).RegisterNode(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Syndicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Syndicate",
	HandlerType: (*SyndicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNode",
			Handler:    _Syndicate_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _Syndicate_RemoveNode_Handler,
		},
		{
			MethodName: "ModNode",
			Handler:    _Syndicate_ModNode_Handler,
		},
		{
			MethodName: "SetConf",
			Handler:    _Syndicate_SetConf_Handler,
		},
		{
			MethodName: "SetActive",
			Handler:    _Syndicate_SetActive_Handler,
		},
		{
			MethodName: "SetCapacity",
			Handler:    _Syndicate_SetCapacity_Handler,
		},
		{
			MethodName: "ReplaceAddresses",
			Handler:    _Syndicate_ReplaceAddresses_Handler,
		},
		{
			MethodName: "ReplaceTiers",
			Handler:    _Syndicate_ReplaceTiers_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Syndicate_GetVersion_Handler,
		},
		{
			MethodName: "GetGlobalConfig",
			Handler:    _Syndicate_GetGlobalConfig_Handler,
		},
		{
			MethodName: "GetNodeConfig",
			Handler:    _Syndicate_GetNodeConfig_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _Syndicate_SearchNodes_Handler,
		},
		{
			MethodName: "GetRing",
			Handler:    _Syndicate_GetRing_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _Syndicate_RegisterNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 837 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0x23, 0x45,
	0x10, 0x8d, 0x33, 0xe3, 0xaf, 0xb2, 0xb3, 0xce, 0xf6, 0xae, 0xc0, 0xe4, 0x04, 0x23, 0x21, 0x2d,
	0xac, 0x12, 0xc0, 0x0b, 0x27, 0x2e, 0x44, 0xb0, 0xda, 0x5c, 0x82, 0x90, 0x03, 0xdc, 0x00, 0xb5,
	0x67, 0xca, 0x49, 0xcb, 0x63, 0xcf, 0xd0, 0xdd, 0x63, 0x64, 0x7e, 0x20, 0x27, 0x7e, 0x14, 0x55,
	0xdd, 0x3d, 0xf6, 0xd8, 0x58, 0xe0, 0x93, 0xdd, 0x35, 0xf5, 0xf1, 0xea, 0x55, 0xbd, 0x82, 0x17,
	0x66, 0xb3, 0xca, 0x54, 0x2a, 0x2d, 0xfe, 0x26, 0x4b, 0x75, 0x53, 0xea, 0xc2, 0x16, 0xa2, 0xed,
	0x7e, 0x92, 0x5f, 0xa0, 0x3b, 0x55, 0xab, 0xc7, 0x7b, 0xf3, 0x28, 0x46, 0xd0, 0x5d, 0xa3, 0x36,
	0xaa, 0x58, 0x8d, 0x5b, 0x1f, 0xb6, 0x5e, 0x45, 0x62, 0x08, 0xb1, 0xa6, 0x6f, 0xe3, 0x73, 0x7a,
	0x0d, 0xf9, 0xf3, 0xac, 0x52, 0x79, 0x86, 0x7a, 0x1c, 0x39, 0xc3, 0x25, 0xf4, 0x32, 0x94, 0x59,
	0xae, 0x56, 0x38, 0x8e, 0x5d, 0x00, 0x59, 0x74, 0x91, 0xe7, 0x33, 0x99, 0x2e, 0xc6, 0x6d, 0xb6,
	0x24, 0xf7, 0x30, 0x78, 0xb0, 0x85, 0xc6, 0x29, 0x9a, 0x2a, 0xb7, 0xff, 0x5d, 0xa2, 0x77, 0x58,
	0xa2, 0x27, 0x9e, 0x41, 0xe7, 0xad, 0xd6, 0x04, 0xce, 0x15, 0xe8, 0x27, 0x37, 0x70, 0xf1, 0x60,
	0xa5, 0xad, 0xcc, 0x14, 0x7f, 0xaf, 0xd0, 0xd8, 0x6d, 0x7c, 0xeb, 0x30, 0xde, 0x25, 0x4c, 0x7e,
	0x82, 0xbe, 0xf7, 0x3f, 0xda, 0xdf, 0x73, 0xe8, 0x73, 0xb0, 0x21, 0x0f, 0xe3, 0x02, 0xfa, 0xe2,
	0x25, 0x0c, 0x43, 0x06, 0x6f, 0x8d, 0x9c, 0x95, 0x60, 0x2c, 0xa5, 0xb1, 0x94, 0xd6, 0xc3, 0x00,
	0xe8, 0xbd, 0x5d, 0x96, 0x76, 0x43, 0x59, 0x93, 0x6b, 0x00, 0x26, 0xd0, 0x97, 0x61, 0x4f, 0xe3,
	0xfe, 0xed, 0x10, 0xd5, 0x35, 0xcf, 0x1d, 0x21, 0x1a, 0xe2, 0xef, 0x8b, 0x0c, 0x05, 0xc0, 0xb9,
	0xca, 0x9c, 0x53, 0xcc, 0x41, 0x32, 0xb5, 0x6a, 0x8d, 0x81, 0x06, 0xa2, 0x31, 0x95, 0xa5, 0x4c,
	0x95, 0xdd, 0x38, 0x00, 0x17, 0xe2, 0x02, 0xda, 0x56, 0x51, 0x1e, 0xaa, 0x1f, 0x11, 0x1e, 0x02,
	0x2e, 0xb3, 0x4c, 0xa3, 0x31, 0x68, 0x88, 0x68, 0x36, 0x11, 0x11, 0x4b, 0xb4, 0x72, 0xdc, 0x71,
	0x80, 0xe9, 0x95, 0x16, 0xab, 0xf9, 0xb8, 0xcb, 0x83, 0x4a, 0xde, 0x40, 0xff, 0xbe, 0xc8, 0xd4,
	0x9c, 0xf1, 0x8a, 0x01, 0x44, 0x0b, 0xdc, 0xb8, 0xca, 0x7d, 0xce, 0xbb, 0x96, 0x79, 0x85, 0xa1,
	0x7b, 0x0f, 0x8a, 0x4b, 0xc6, 0xc9, 0x1d, 0xf4, 0xb8, 0xaf, 0x6f, 0x29, 0x8d, 0xf8, 0x68, 0xaf,
	0xab, 0xc1, 0xe4, 0xb9, 0xdf, 0xa1, 0x9b, 0x46, 0xe3, 0x1f, 0x84, 0x8a, 0xe7, 0xce, 0x61, 0x10,
	0x1c, 0x38, 0x9a, 0x18, 0x8a, 0x5d, 0x96, 0x1a, 0x54, 0xcb, 0x6d, 0xcf, 0xfb, 0x30, 0xa2, 0x06,
	0xac, 0xd4, 0x96, 0x67, 0xa9, 0x34, 0x66, 0x61, 0x66, 0x0b, 0x18, 0x4d, 0xf1, 0x51, 0x31, 0xdd,
	0xf5, 0x94, 0x89, 0x90, 0xa7, 0xc2, 0xd8, 0x95, 0x5c, 0xe2, 0x0e, 0x38, 0x33, 0xc0, 0x63, 0x8b,
	0xfc, 0xd3, 0xf3, 0x13, 0xb9, 0xe7, 0x2b, 0xf2, 0x97, 0x3a, 0xfb, 0x43, 0x6a, 0xbf, 0x99, 0x83,
	0xc9, 0x7b, 0x01, 0xd0, 0x5d, 0x30, 0xff, 0xa0, 0x8b, 0xb9, 0xca, 0x31, 0xf9, 0x15, 0x46, 0x07,
	0x26, 0x2e, 0xb6, 0xc4, 0xa5, 0x2d, 0xac, 0xcc, 0xc3, 0x7c, 0x68, 0x88, 0x64, 0x99, 0x6b, 0xf4,
	0x3c, 0xc5, 0xae, 0x93, 0xb2, 0xf2, 0xdb, 0x11, 0x89, 0x2b, 0x68, 0x67, 0xca, 0x2c, 0xfc, 0x70,
	0x76, 0xbd, 0x7f, 0x47, 0xb6, 0xe4, 0x1b, 0x88, 0xf9, 0x97, 0x47, 0x9c, 0xe1, 0x5a, 0xa5, 0x35,
	0x7e, 0xca, 0x50, 0x4a, 0xfb, 0x14, 0x78, 0xa7, 0x97, 0x51, 0x7f, 0xa2, 0x67, 0x9e, 0x5f, 0x95,
	0x21, 0x3a, 0x62, 0x37, 0x87, 0xd7, 0x00, 0xbc, 0x30, 0xcc, 0xa0, 0x72, 0x3b, 0x9c, 0x17, 0xa9,
	0xcc, 0xb7, 0xbb, 0xb3, 0xa7, 0xd1, 0xe4, 0x63, 0x88, 0x79, 0x26, 0xff, 0x23, 0xe5, 0xe4, 0x53,
	0x18, 0x3e, 0xa0, 0xd4, 0xe9, 0x53, 0x90, 0x25, 0x75, 0xb0, 0xa2, 0x1a, 0x3c, 0xde, 0x66, 0x07,
	0x5c, 0x77, 0xf2, 0x77, 0xcb, 0x2f, 0x02, 0xb5, 0x61, 0xc5, 0x35, 0xb4, 0x9d, 0x9c, 0xc5, 0xb3,
	0xc6, 0x06, 0xd0, 0x56, 0x5d, 0x89, 0xf0, 0x6e, 0x88, 0x3d, 0x39, 0x13, 0x37, 0xd0, 0x99, 0x22,
	0x01, 0xb1, 0x27, 0xfa, 0x4f, 0xa0, 0x13, 0xd6, 0xe9, 0xe5, 0xf6, 0x7b, 0x43, 0xed, 0x57, 0x97,
	0x7b, 0x56, 0x56, 0xdf, 0x99, 0x83, 0x84, 0xb6, 0x2a, 0x4f, 0x2b, 0x31, 0xf9, 0xab, 0x4d, 0x27,
	0xa1, 0x3e, 0x87, 0xe2, 0x35, 0x74, 0x6f, 0xb3, 0xcc, 0x09, 0xb2, 0xd9, 0xf4, 0xd5, 0xbf, 0x17,
	0xdc, 0x75, 0x03, 0x53, 0x5c, 0x16, 0x6b, 0x3c, 0xd1, 0xff, 0x73, 0xe8, 0x92, 0xec, 0x9c, 0x73,
	0x0d, 0x7c, 0x2b, 0xc3, 0xe3, 0x11, 0x04, 0x87, 0x7a, 0x71, 0x62, 0x69, 0x2a, 0xe8, 0xb8, 0xf3,
	0x35, 0x35, 0x82, 0xf6, 0xd6, 0x1d, 0x8e, 0x13, 0xd0, 0x7c, 0x46, 0x97, 0x98, 0x72, 0x87, 0xbb,
	0x72, 0x42, 0xc0, 0x97, 0x70, 0x39, 0xc5, 0x32, 0x97, 0x29, 0xde, 0xd6, 0xb7, 0xe6, 0xa4, 0xa6,
	0x87, 0x21, 0xea, 0x47, 0x16, 0xe4, 0x09, 0x11, 0x13, 0x80, 0x77, 0x68, 0x7f, 0xf6, 0xeb, 0x2a,
	0x46, 0xc1, 0xa5, 0xbe, 0xaf, 0xc7, 0x63, 0xbe, 0x82, 0x11, 0xc5, 0xbc, 0xcb, 0x8b, 0x99, 0xcc,
	0x6b, 0x65, 0x1c, 0x06, 0x8e, 0x1a, 0x81, 0xee, 0x0e, 0x31, 0x07, 0x17, 0x14, 0xd6, 0x90, 0xd3,
	0x1e, 0xba, 0x23, 0x01, 0x5f, 0x30, 0x69, 0x2c, 0x14, 0x76, 0x38, 0x68, 0xe6, 0x45, 0xbd, 0x5f,
	0x0d, 0x25, 0x51, 0xc8, 0x27, 0xd0, 0xa5, 0x1a, 0x5e, 0x85, 0x87, 0x90, 0x06, 0x8d, 0x0a, 0xe4,
	0xfa, 0x35, 0x73, 0xe5, 0x2f, 0x9d, 0xdb, 0x92, 0xfa, 0x48, 0x1d, 0x9c, 0xbf, 0x2d, 0x05, 0x3b,
	0xe0, 0xc9, 0xd9, 0xac, 0xe3, 0x6c, 0x6f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xce, 0x58,
	0x63, 0xdd, 0x07, 0x00, 0x00,
}
