// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	ModAccount
	CreateAcctRequest
	CreateAcctResponse
	ListAcctRequest
	ListAcctResponse
	ShowAcctRequest
	ShowAcctResponse
	DeleteAcctRequest
	DeleteAcctResponse
	UpdateAcctRequest
	UpdateAcctResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Values that can be changed on an account
type ModAccount struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *ModAccount) Reset()                    { *m = ModAccount{} }
func (m *ModAccount) String() string            { return proto.CompactTextString(m) }
func (*ModAccount) ProtoMessage()               {}
func (*ModAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Request to Create an account
type CreateAcctRequest struct {
	Acctname string `protobuf:"bytes,1,opt,name=acctname" json:"acctname,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *CreateAcctRequest) Reset()                    { *m = CreateAcctRequest{} }
func (m *CreateAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAcctRequest) ProtoMessage()               {}
func (*CreateAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Response for account Create results
type CreateAcctResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *CreateAcctResponse) Reset()                    { *m = CreateAcctResponse{} }
func (m *CreateAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAcctResponse) ProtoMessage()               {}
func (*CreateAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Request to show an account
type ListAcctRequest struct {
	Superkey string `protobuf:"bytes,1,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *ListAcctRequest) Reset()                    { *m = ListAcctRequest{} }
func (m *ListAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*ListAcctRequest) ProtoMessage()               {}
func (*ListAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Response for account Show results
type ListAcctResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ListAcctResponse) Reset()                    { *m = ListAcctResponse{} }
func (m *ListAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAcctResponse) ProtoMessage()               {}
func (*ListAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Request to show an account
type ShowAcctRequest struct {
	Acctnum  string `protobuf:"bytes,1,opt,name=acctnum" json:"acctnum,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *ShowAcctRequest) Reset()                    { *m = ShowAcctRequest{} }
func (m *ShowAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowAcctRequest) ProtoMessage()               {}
func (*ShowAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Response for account Show results
type ShowAcctResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ShowAcctResponse) Reset()                    { *m = ShowAcctResponse{} }
func (m *ShowAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowAcctResponse) ProtoMessage()               {}
func (*ShowAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// Request to Delete account
type DeleteAcctRequest struct {
	Acctnum  string `protobuf:"bytes,1,opt,name=acctnum" json:"acctnum,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *DeleteAcctRequest) Reset()                    { *m = DeleteAcctRequest{} }
func (m *DeleteAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAcctRequest) ProtoMessage()               {}
func (*DeleteAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Response for account Delete results
type DeleteAcctResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteAcctResponse) Reset()                    { *m = DeleteAcctResponse{} }
func (m *DeleteAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAcctResponse) ProtoMessage()               {}
func (*DeleteAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// Request to Update account's api key
type UpdateAcctRequest struct {
	Acctnum  string      `protobuf:"bytes,1,opt,name=acctnum" json:"acctnum,omitempty"`
	Superkey string      `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
	ModAcct  *ModAccount `protobuf:"bytes,3,opt,name=modAcct" json:"modAcct,omitempty"`
}

func (m *UpdateAcctRequest) Reset()                    { *m = UpdateAcctRequest{} }
func (m *UpdateAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAcctRequest) ProtoMessage()               {}
func (*UpdateAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateAcctRequest) GetModAcct() *ModAccount {
	if m != nil {
		return m.ModAcct
	}
	return nil
}

// Response for account Update results
type UpdateAcctResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateAcctResponse) Reset()                    { *m = UpdateAcctResponse{} }
func (m *UpdateAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateAcctResponse) ProtoMessage()               {}
func (*UpdateAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*ModAccount)(nil), "account.ModAccount")
	proto.RegisterType((*CreateAcctRequest)(nil), "account.CreateAcctRequest")
	proto.RegisterType((*CreateAcctResponse)(nil), "account.CreateAcctResponse")
	proto.RegisterType((*ListAcctRequest)(nil), "account.ListAcctRequest")
	proto.RegisterType((*ListAcctResponse)(nil), "account.ListAcctResponse")
	proto.RegisterType((*ShowAcctRequest)(nil), "account.ShowAcctRequest")
	proto.RegisterType((*ShowAcctResponse)(nil), "account.ShowAcctResponse")
	proto.RegisterType((*DeleteAcctRequest)(nil), "account.DeleteAcctRequest")
	proto.RegisterType((*DeleteAcctResponse)(nil), "account.DeleteAcctResponse")
	proto.RegisterType((*UpdateAcctRequest)(nil), "account.UpdateAcctRequest")
	proto.RegisterType((*UpdateAcctResponse)(nil), "account.UpdateAcctResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for AccountApi service

type AccountApiClient interface {
	CreateAcct(ctx context.Context, in *CreateAcctRequest, opts ...grpc.CallOption) (*CreateAcctResponse, error)
	ListAcct(ctx context.Context, in *ListAcctRequest, opts ...grpc.CallOption) (*ListAcctResponse, error)
	ShowAcct(ctx context.Context, in *ShowAcctRequest, opts ...grpc.CallOption) (*ShowAcctResponse, error)
	DeleteAcct(ctx context.Context, in *DeleteAcctRequest, opts ...grpc.CallOption) (*DeleteAcctResponse, error)
	UpdateAcct(ctx context.Context, in *UpdateAcctRequest, opts ...grpc.CallOption) (*UpdateAcctResponse, error)
}

type accountApiClient struct {
	cc *grpc.ClientConn
}

func NewAccountApiClient(cc *grpc.ClientConn) AccountApiClient {
	return &accountApiClient{cc}
}

func (c *accountApiClient) CreateAcct(ctx context.Context, in *CreateAcctRequest, opts ...grpc.CallOption) (*CreateAcctResponse, error) {
	out := new(CreateAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/CreateAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) ListAcct(ctx context.Context, in *ListAcctRequest, opts ...grpc.CallOption) (*ListAcctResponse, error) {
	out := new(ListAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/ListAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) ShowAcct(ctx context.Context, in *ShowAcctRequest, opts ...grpc.CallOption) (*ShowAcctResponse, error) {
	out := new(ShowAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/ShowAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) DeleteAcct(ctx context.Context, in *DeleteAcctRequest, opts ...grpc.CallOption) (*DeleteAcctResponse, error) {
	out := new(DeleteAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/DeleteAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) UpdateAcct(ctx context.Context, in *UpdateAcctRequest, opts ...grpc.CallOption) (*UpdateAcctResponse, error) {
	out := new(UpdateAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/UpdateAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountApi service

type AccountApiServer interface {
	CreateAcct(context.Context, *CreateAcctRequest) (*CreateAcctResponse, error)
	ListAcct(context.Context, *ListAcctRequest) (*ListAcctResponse, error)
	ShowAcct(context.Context, *ShowAcctRequest) (*ShowAcctResponse, error)
	DeleteAcct(context.Context, *DeleteAcctRequest) (*DeleteAcctResponse, error)
	UpdateAcct(context.Context, *UpdateAcctRequest) (*UpdateAcctResponse, error)
}

func RegisterAccountApiServer(s *grpc.Server, srv AccountApiServer) {
	s.RegisterService(&_AccountApi_serviceDesc, srv)
}

func _AccountApi_CreateAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).CreateAcct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountApi/CreateAcct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).CreateAcct(ctx, req.(*CreateAcctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApi_ListAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).ListAcct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountApi/ListAcct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).ListAcct(ctx, req.(*ListAcctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApi_ShowAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).ShowAcct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountApi/ShowAcct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).ShowAcct(ctx, req.(*ShowAcctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApi_DeleteAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).DeleteAcct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountApi/DeleteAcct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).DeleteAcct(ctx, req.(*DeleteAcctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApi_UpdateAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApiServer).UpdateAcct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountApi/UpdateAcct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApiServer).UpdateAcct(ctx, req.(*UpdateAcctRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountApi",
	HandlerType: (*AccountApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAcct",
			Handler:    _AccountApi_CreateAcct_Handler,
		},
		{
			MethodName: "ListAcct",
			Handler:    _AccountApi_ListAcct_Handler,
		},
		{
			MethodName: "ShowAcct",
			Handler:    _AccountApi_ShowAcct_Handler,
		},
		{
			MethodName: "DeleteAcct",
			Handler:    _AccountApi_DeleteAcct_Handler,
		},
		{
			MethodName: "UpdateAcct",
			Handler:    _AccountApi_UpdateAcct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x29, 0x2a, 0xe0, 0x35, 0x06, 0xb9, 0x1a, 0x53, 0xeb, 0xc6, 0x74, 0xe5, 0x42, 0x58,
	0xe0, 0x13, 0x10, 0x89, 0xc4, 0xf8, 0xb3, 0xc0, 0xf8, 0x00, 0x23, 0x4c, 0x22, 0x01, 0x3a, 0x95,
	0x99, 0x46, 0x79, 0x68, 0xdf, 0xc1, 0x71, 0x3a, 0xed, 0x5c, 0x5a, 0xa2, 0x49, 0xe3, 0x8e, 0xd3,
	0xb9, 0xf9, 0xce, 0xfd, 0x39, 0x01, 0x0e, 0xd9, 0x64, 0x22, 0x92, 0x48, 0xf5, 0xe2, 0x95, 0x50,
	0x02, 0x9b, 0x56, 0x86, 0x4f, 0x00, 0x8f, 0x62, 0x3a, 0x48, 0x15, 0x22, 0xec, 0x46, 0x6c, 0xc9,
	0x7d, 0xef, 0xc2, 0xbb, 0xdc, 0x1f, 0x9b, 0xdf, 0x78, 0x02, 0x7b, 0x4a, 0xcc, 0x79, 0xe4, 0xd7,
	0xcd, 0xc7, 0x54, 0xe0, 0x29, 0x34, 0xa4, 0x62, 0x2a, 0x91, 0xfe, 0x8e, 0xf9, 0x6c, 0x55, 0x78,
	0x0f, 0x9d, 0x9b, 0x15, 0x67, 0x8a, 0x6b, 0xa4, 0x1a, 0xf3, 0xf7, 0x84, 0x4b, 0x85, 0x01, 0xb4,
	0xb4, 0x9f, 0x22, 0xe8, 0x5c, 0xff, 0xbc, 0xc9, 0x24, 0xe6, 0xab, 0x39, 0x5f, 0x5b, 0x87, 0x5c,
	0x87, 0x57, 0x80, 0x14, 0x26, 0x63, 0x11, 0x49, 0x4e, 0xac, 0xbd, 0x0d, 0xeb, 0x2e, 0xb4, 0x1f,
	0x66, 0x52, 0x15, 0x8c, 0x73, 0xb8, 0x57, 0x80, 0x0f, 0xe1, 0xc8, 0x95, 0x5b, 0xb4, 0x0f, 0xcd,
	0x98, 0xad, 0x17, 0x82, 0x4d, 0x6d, 0x79, 0x26, 0x89, 0x69, 0x7d, 0xc3, 0x74, 0x04, 0xed, 0xe7,
	0x37, 0xf1, 0x41, 0x4d, 0x35, 0xc4, 0x4c, 0x97, 0x2c, 0x33, 0x88, 0x95, 0xbf, 0xce, 0xaa, 0xdb,
	0x71, 0xa0, 0xca, 0xed, 0xdc, 0x41, 0x67, 0xc8, 0x17, 0x7c, 0x73, 0xfd, 0xd5, 0x1a, 0xd2, 0xcb,
	0xa7, 0xa8, 0x3f, 0x96, 0xff, 0x09, 0x9d, 0x97, 0x78, 0xca, 0xfe, 0xc1, 0x18, 0xbb, 0xd0, 0x5c,
	0x9a, 0x48, 0x2a, 0x93, 0xad, 0x83, 0xfe, 0x71, 0x2f, 0x0b, 0xaf, 0x8b, 0xea, 0x38, 0xab, 0x09,
	0x6f, 0x01, 0xa9, 0x73, 0xd5, 0xd5, 0xf5, 0xbf, 0xea, 0x00, 0x16, 0x3e, 0x88, 0x67, 0x38, 0x02,
	0x70, 0xd9, 0xc3, 0x20, 0x6f, 0xa1, 0x94, 0xee, 0xe0, 0x7c, 0xeb, 0x5b, 0xda, 0x47, 0x58, 0xc3,
	0x01, 0xb4, 0xb2, 0x9c, 0xa1, 0x9f, 0x97, 0x16, 0x92, 0x1a, 0x9c, 0x6d, 0x79, 0xa1, 0x88, 0x2c,
	0x1b, 0x04, 0x51, 0xc8, 0x1d, 0x41, 0x14, 0x83, 0xa4, 0x11, 0x7a, 0x1c, 0x77, 0x4d, 0x32, 0x4e,
	0x29, 0x2d, 0x64, 0x9c, 0xf2, 0xf9, 0x53, 0x90, 0x5b, 0x37, 0x01, 0x95, 0xae, 0x4f, 0x40, 0xe5,
	0xfb, 0x84, 0xb5, 0xd7, 0x86, 0xf9, 0x27, 0xba, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xda,
	0xe2, 0x73, 0x9a, 0x04, 0x00, 0x00,
}
