// Code generated by protoc-gen-go.
// source: cmdctrlsvc.proto
// DO NOT EDIT!

/*
Package cmdctrlsvc is a generated protocol buffer package.

It is generated from these files:
	cmdctrlsvc.proto

It has these top-level messages:
	RingUpdateResult
	StatsMsg
	EmptyMsg
	StatusMsg
	Ring
	HealthCheckMsg
*/
package cmdctrlsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RingUpdateResult struct {
	Newversion int64 `protobuf:"varint,1,opt,name=newversion" json:"newversion,omitempty"`
}

func (m *RingUpdateResult) Reset()                    { *m = RingUpdateResult{} }
func (m *RingUpdateResult) String() string            { return proto.CompactTextString(m) }
func (*RingUpdateResult) ProtoMessage()               {}
func (*RingUpdateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatsMsg struct {
	Statsjson []byte `protobuf:"bytes,1,opt,name=statsjson,proto3" json:"statsjson,omitempty"`
}

func (m *StatsMsg) Reset()                    { *m = StatsMsg{} }
func (m *StatsMsg) String() string            { return proto.CompactTextString(m) }
func (*StatsMsg) ProtoMessage()               {}
func (*StatsMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StatusMsg struct {
	Status bool   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *StatusMsg) Reset()                    { *m = StatusMsg{} }
func (m *StatusMsg) String() string            { return proto.CompactTextString(m) }
func (*StatusMsg) ProtoMessage()               {}
func (*StatusMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Ring struct {
	Version int64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ring    []byte `protobuf:"bytes,2,opt,name=ring,proto3" json:"ring,omitempty"`
}

func (m *Ring) Reset()                    { *m = Ring{} }
func (m *Ring) String() string            { return proto.CompactTextString(m) }
func (*Ring) ProtoMessage()               {}
func (*Ring) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type HealthCheckMsg struct {
	Status bool   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Ts     int64  `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
}

func (m *HealthCheckMsg) Reset()                    { *m = HealthCheckMsg{} }
func (m *HealthCheckMsg) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckMsg) ProtoMessage()               {}
func (*HealthCheckMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*RingUpdateResult)(nil), "cmdctrlsvc.RingUpdateResult")
	proto.RegisterType((*StatsMsg)(nil), "cmdctrlsvc.StatsMsg")
	proto.RegisterType((*EmptyMsg)(nil), "cmdctrlsvc.EmptyMsg")
	proto.RegisterType((*StatusMsg)(nil), "cmdctrlsvc.StatusMsg")
	proto.RegisterType((*Ring)(nil), "cmdctrlsvc.Ring")
	proto.RegisterType((*HealthCheckMsg)(nil), "cmdctrlsvc.HealthCheckMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for CmdCtrl service

type CmdCtrlClient interface {
	RingUpdate(ctx context.Context, in *Ring, opts ...grpc.CallOption) (*RingUpdateResult, error)
	Reload(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Restart(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Start(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Stop(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Exit(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Stats(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatsMsg, error)
	HealthCheck(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*HealthCheckMsg, error)
}

type cmdCtrlClient struct {
	cc *grpc.ClientConn
}

func NewCmdCtrlClient(cc *grpc.ClientConn) CmdCtrlClient {
	return &cmdCtrlClient{cc}
}

func (c *cmdCtrlClient) RingUpdate(ctx context.Context, in *Ring, opts ...grpc.CallOption) (*RingUpdateResult, error) {
	out := new(RingUpdateResult)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/RingUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Reload(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Reload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Restart(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Restart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Start(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Stop(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Exit(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Exit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Stats(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatsMsg, error) {
	out := new(StatsMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Stats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) HealthCheck(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*HealthCheckMsg, error) {
	out := new(HealthCheckMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmdCtrl service

type CmdCtrlServer interface {
	RingUpdate(context.Context, *Ring) (*RingUpdateResult, error)
	Reload(context.Context, *EmptyMsg) (*StatusMsg, error)
	Restart(context.Context, *EmptyMsg) (*StatusMsg, error)
	Start(context.Context, *EmptyMsg) (*StatusMsg, error)
	Stop(context.Context, *EmptyMsg) (*StatusMsg, error)
	Exit(context.Context, *EmptyMsg) (*StatusMsg, error)
	Stats(context.Context, *EmptyMsg) (*StatsMsg, error)
	HealthCheck(context.Context, *EmptyMsg) (*HealthCheckMsg, error)
}

func RegisterCmdCtrlServer(s *grpc.Server, srv CmdCtrlServer) {
	s.RegisterService(&_CmdCtrl_serviceDesc, srv)
}

func _CmdCtrl_RingUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ring)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).RingUpdate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Reload(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Restart(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Start(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Stop(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Exit(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Stats(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).HealthCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _CmdCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdctrlsvc.CmdCtrl",
	HandlerType: (*CmdCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RingUpdate",
			Handler:    _CmdCtrl_RingUpdate_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _CmdCtrl_Reload_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _CmdCtrl_Restart_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _CmdCtrl_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CmdCtrl_Stop_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _CmdCtrl_Exit_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _CmdCtrl_Stats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CmdCtrl_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xdb, 0xa6, 0x9f, 0x6f, 0x4b, 0xad, 0x4b, 0x85, 0x52, 0x14, 0x64, 0x41, 0xe9, 0xa9,
	0x07, 0xc5, 0xaf, 0x8b, 0x20, 0xa5, 0xe0, 0xc5, 0x4b, 0x82, 0x3f, 0x20, 0x26, 0x4b, 0x1a, 0xcd,
	0x17, 0xd9, 0x69, 0xd5, 0xff, 0xea, 0x8f, 0x71, 0xb3, 0x54, 0xbb, 0x2d, 0x14, 0x31, 0xb7, 0xcc,
	0x3b, 0xef, 0x33, 0x93, 0x99, 0x1d, 0x0c, 0xbc, 0xd8, 0xf7, 0x28, 0x8f, 0xe4, 0xca, 0x9b, 0x66,
	0x79, 0x4a, 0x29, 0xc3, 0x46, 0xe1, 0xe7, 0x18, 0xd8, 0x61, 0x12, 0x3c, 0x67, 0xbe, 0x4b, 0xc2,
	0x16, 0x72, 0x19, 0x11, 0x63, 0x40, 0x22, 0xde, 0x57, 0x22, 0x97, 0x61, 0x9a, 0x8c, 0xaa, 0xa7,
	0xd5, 0x89, 0xc5, 0x4f, 0xd0, 0x76, 0xc8, 0x25, 0xf9, 0x24, 0x03, 0x76, 0x88, 0x8e, 0x2c, 0xbe,
	0x5f, 0xe5, 0x3a, 0xdd, 0xe3, 0x40, 0x7b, 0x1e, 0x67, 0xf4, 0xa9, 0xd2, 0x7c, 0x82, 0x4e, 0x61,
	0x5d, 0x6a, 0x6f, 0x1f, 0x4d, 0xa9, 0x03, 0x6d, 0x6c, 0xb3, 0x2e, 0xac, 0x58, 0x06, 0xa3, 0x9a,
	0x0a, 0x3a, 0xfc, 0x0c, 0xf5, 0xa2, 0x39, 0x3b, 0x40, 0x6b, 0xab, 0x1b, 0xeb, 0xa1, 0x9e, 0xab,
	0x84, 0xb6, 0xf5, 0xf8, 0x1d, 0xfa, 0x8f, 0xc2, 0x8d, 0x68, 0x31, 0x5b, 0x08, 0xef, 0xed, 0xaf,
	0xaa, 0xea, 0xef, 0x6b, 0x24, 0x47, 0x56, 0x51, 0xe8, 0xe2, 0xcb, 0x42, 0x6b, 0x16, 0xfb, 0x33,
	0x35, 0x2d, 0xbb, 0x07, 0x36, 0xa3, 0xb2, 0xc1, 0xd4, 0xd8, 0x4b, 0xa1, 0x8f, 0x8f, 0x77, 0x15,
	0x73, 0x29, 0xbc, 0xc2, 0x6e, 0xd0, 0xb4, 0x45, 0x94, 0xba, 0x3e, 0x1b, 0x9a, 0xce, 0x9f, 0xb9,
	0xc7, 0x47, 0xa6, 0xfa, 0xbb, 0x01, 0x05, 0xde, 0xa2, 0xa5, 0x8a, 0x90, 0x9b, 0xd3, 0x7f, 0xc9,
	0x6b, 0x34, 0x9c, 0x32, 0xdc, 0x15, 0xea, 0x0e, 0xa5, 0x59, 0x09, 0x6c, 0xfe, 0x11, 0x96, 0xe8,
	0xd6, 0xd0, 0xb7, 0xb1, 0x87, 0x1b, 0xee, 0x72, 0x6b, 0xec, 0x01, 0x5d, 0xe3, 0x59, 0xf7, 0xc0,
	0x63, 0x53, 0xdd, 0xbe, 0x02, 0x5e, 0x79, 0x69, 0xea, 0x83, 0xbe, 0xfc, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0xd7, 0x88, 0x0c, 0xe4, 0x02, 0x00, 0x00,
}
