// Code generated by protoc-gen-gogo.
// source: cmdctrlsvc.proto
// DO NOT EDIT!

/*
	Package cmdctrlsvc is a generated protocol buffer package.

	It is generated from these files:
		cmdctrlsvc.proto

	It has these top-level messages:
		RingUpdateResult
		StatsMsg
		EmptyMsg
		StatusMsg
		Ring
		HealthCheckMsg
*/
package cmdctrlsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RingUpdateResult struct {
	Newversion int64 `protobuf:"varint,1,opt,name=newversion,proto3" json:"newversion,omitempty"`
}

func (m *RingUpdateResult) Reset()                    { *m = RingUpdateResult{} }
func (m *RingUpdateResult) String() string            { return proto.CompactTextString(m) }
func (*RingUpdateResult) ProtoMessage()               {}
func (*RingUpdateResult) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{0} }

type StatsMsg struct {
	Statsjson []byte `protobuf:"bytes,1,opt,name=statsjson,proto3" json:"statsjson,omitempty"`
}

func (m *StatsMsg) Reset()                    { *m = StatsMsg{} }
func (m *StatsMsg) String() string            { return proto.CompactTextString(m) }
func (*StatsMsg) ProtoMessage()               {}
func (*StatsMsg) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{1} }

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{2} }

type StatusMsg struct {
	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *StatusMsg) Reset()                    { *m = StatusMsg{} }
func (m *StatusMsg) String() string            { return proto.CompactTextString(m) }
func (*StatusMsg) ProtoMessage()               {}
func (*StatusMsg) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{3} }

type Ring struct {
	Version int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Ring    []byte `protobuf:"bytes,2,opt,name=ring,proto3" json:"ring,omitempty"`
}

func (m *Ring) Reset()                    { *m = Ring{} }
func (m *Ring) String() string            { return proto.CompactTextString(m) }
func (*Ring) ProtoMessage()               {}
func (*Ring) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{4} }

type HealthCheckMsg struct {
	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ts     int64  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (m *HealthCheckMsg) Reset()                    { *m = HealthCheckMsg{} }
func (m *HealthCheckMsg) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckMsg) ProtoMessage()               {}
func (*HealthCheckMsg) Descriptor() ([]byte, []int) { return fileDescriptorCmdctrlsvc, []int{5} }

func init() {
	proto.RegisterType((*RingUpdateResult)(nil), "cmdctrlsvc.RingUpdateResult")
	proto.RegisterType((*StatsMsg)(nil), "cmdctrlsvc.StatsMsg")
	proto.RegisterType((*EmptyMsg)(nil), "cmdctrlsvc.EmptyMsg")
	proto.RegisterType((*StatusMsg)(nil), "cmdctrlsvc.StatusMsg")
	proto.RegisterType((*Ring)(nil), "cmdctrlsvc.Ring")
	proto.RegisterType((*HealthCheckMsg)(nil), "cmdctrlsvc.HealthCheckMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for CmdCtrl service

type CmdCtrlClient interface {
	RingUpdate(ctx context.Context, in *Ring, opts ...grpc.CallOption) (*RingUpdateResult, error)
	Reload(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Restart(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Start(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Stop(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Exit(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error)
	Stats(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatsMsg, error)
	HealthCheck(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*HealthCheckMsg, error)
}

type cmdCtrlClient struct {
	cc *grpc.ClientConn
}

func NewCmdCtrlClient(cc *grpc.ClientConn) CmdCtrlClient {
	return &cmdCtrlClient{cc}
}

func (c *cmdCtrlClient) RingUpdate(ctx context.Context, in *Ring, opts ...grpc.CallOption) (*RingUpdateResult, error) {
	out := new(RingUpdateResult)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/RingUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Reload(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Reload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Restart(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Restart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Start(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Stop(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Exit(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusMsg, error) {
	out := new(StatusMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Exit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) Stats(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatsMsg, error) {
	out := new(StatsMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/Stats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdCtrlClient) HealthCheck(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*HealthCheckMsg, error) {
	out := new(HealthCheckMsg)
	err := grpc.Invoke(ctx, "/cmdctrlsvc.CmdCtrl/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmdCtrl service

type CmdCtrlServer interface {
	RingUpdate(context.Context, *Ring) (*RingUpdateResult, error)
	Reload(context.Context, *EmptyMsg) (*StatusMsg, error)
	Restart(context.Context, *EmptyMsg) (*StatusMsg, error)
	Start(context.Context, *EmptyMsg) (*StatusMsg, error)
	Stop(context.Context, *EmptyMsg) (*StatusMsg, error)
	Exit(context.Context, *EmptyMsg) (*StatusMsg, error)
	Stats(context.Context, *EmptyMsg) (*StatsMsg, error)
	HealthCheck(context.Context, *EmptyMsg) (*HealthCheckMsg, error)
}

func RegisterCmdCtrlServer(s *grpc.Server, srv CmdCtrlServer) {
	s.RegisterService(&_CmdCtrl_serviceDesc, srv)
}

func _CmdCtrl_RingUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Ring)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).RingUpdate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Reload(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Restart(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Start(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Stop(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Exit(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).Stats(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CmdCtrl_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CmdCtrlServer).HealthCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _CmdCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdctrlsvc.CmdCtrl",
	HandlerType: (*CmdCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RingUpdate",
			Handler:    _CmdCtrl_RingUpdate_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _CmdCtrl_Reload_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _CmdCtrl_Restart_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _CmdCtrl_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CmdCtrl_Stop_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _CmdCtrl_Exit_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _CmdCtrl_Stats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CmdCtrl_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

func (m *RingUpdateResult) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *RingUpdateResult) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Newversion != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(m.Newversion))
	}
	return i, nil
}

func (m *StatsMsg) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *StatsMsg) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Statsjson) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(len(m.Statsjson)))
		i += copy(data[i:], m.Statsjson)
	}
	return i, nil
}

func (m *EmptyMsg) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *EmptyMsg) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *StatusMsg) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *StatusMsg) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status {
		data[i] = 0x8
		i++
		if m.Status {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if len(m.Msg) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(len(m.Msg)))
		i += copy(data[i:], m.Msg)
	}
	return i, nil
}

func (m *Ring) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Ring) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(m.Version))
	}
	if len(m.Ring) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(len(m.Ring)))
		i += copy(data[i:], m.Ring)
	}
	return i, nil
}

func (m *HealthCheckMsg) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *HealthCheckMsg) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status {
		data[i] = 0x8
		i++
		if m.Status {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if len(m.Msg) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(len(m.Msg)))
		i += copy(data[i:], m.Msg)
	}
	if m.Ts != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintCmdctrlsvc(data, i, uint64(m.Ts))
	}
	return i, nil
}

func encodeFixed64Cmdctrlsvc(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Cmdctrlsvc(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintCmdctrlsvc(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *RingUpdateResult) Size() (n int) {
	var l int
	_ = l
	if m.Newversion != 0 {
		n += 1 + sovCmdctrlsvc(uint64(m.Newversion))
	}
	return n
}

func (m *StatsMsg) Size() (n int) {
	var l int
	_ = l
	l = len(m.Statsjson)
	if l > 0 {
		n += 1 + l + sovCmdctrlsvc(uint64(l))
	}
	return n
}

func (m *EmptyMsg) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *StatusMsg) Size() (n int) {
	var l int
	_ = l
	if m.Status {
		n += 2
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovCmdctrlsvc(uint64(l))
	}
	return n
}

func (m *Ring) Size() (n int) {
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovCmdctrlsvc(uint64(m.Version))
	}
	l = len(m.Ring)
	if l > 0 {
		n += 1 + l + sovCmdctrlsvc(uint64(l))
	}
	return n
}

func (m *HealthCheckMsg) Size() (n int) {
	var l int
	_ = l
	if m.Status {
		n += 2
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovCmdctrlsvc(uint64(l))
	}
	if m.Ts != 0 {
		n += 1 + sovCmdctrlsvc(uint64(m.Ts))
	}
	return n
}

func sovCmdctrlsvc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCmdctrlsvc(x uint64) (n int) {
	return sovCmdctrlsvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RingUpdateResult) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RingUpdateResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RingUpdateResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newversion", wireType)
			}
			m.Newversion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Newversion |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatsMsg) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatsMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatsMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statsjson", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Statsjson = append(m.Statsjson[:0], data[iNdEx:postIndex]...)
			if m.Statsjson == nil {
				m.Statsjson = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyMsg) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusMsg) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ring) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ring: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ring: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Version |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ring", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ring = append(m.Ring[:0], data[iNdEx:postIndex]...)
			if m.Ring == nil {
				m.Ring = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HealthCheckMsg) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HealthCheckMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HealthCheckMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Status = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ts", wireType)
			}
			m.Ts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Ts |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCmdctrlsvc(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCmdctrlsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCmdctrlsvc(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCmdctrlsvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCmdctrlsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCmdctrlsvc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCmdctrlsvc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCmdctrlsvc(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCmdctrlsvc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCmdctrlsvc   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorCmdctrlsvc = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x81, 0xf2, 0xf7, 0x7c, 0x84, 0x34, 0x13, 0x3e, 0xd3, 0x10, 0x42, 0xcc, 0xac, 0x58,
	0xb1, 0x40, 0x51, 0x57, 0x26, 0x4a, 0x48, 0x8c, 0x89, 0x9b, 0x21, 0x3e, 0x40, 0x6d, 0x27, 0x80,
	0xb6, 0xb4, 0xe9, 0x0c, 0xa8, 0x6f, 0xe2, 0x23, 0xb9, 0xf4, 0x01, 0x5c, 0x18, 0x7d, 0x11, 0xa7,
	0x13, 0x90, 0x81, 0x84, 0x05, 0x5d, 0x4c, 0x72, 0xef, 0xc9, 0xf9, 0xf5, 0x4e, 0x4e, 0xef, 0xc0,
	0xf6, 0x42, 0xdf, 0x93, 0x49, 0x20, 0x96, 0x5e, 0x2f, 0x4e, 0x22, 0x19, 0x11, 0x6c, 0x14, 0xda,
	0x87, 0xcd, 0x66, 0xf3, 0xc9, 0x7d, 0xec, 0xbb, 0x92, 0x33, 0x2e, 0x16, 0x81, 0x24, 0x1d, 0x60,
	0xce, 0x9f, 0x97, 0x3c, 0x11, 0xb3, 0x68, 0xee, 0xe4, 0x8f, 0xf3, 0x5d, 0x8b, 0x19, 0x0a, 0xed,
	0xa2, 0x3a, 0x96, 0xae, 0x14, 0x77, 0x62, 0x42, 0xda, 0xa8, 0x89, 0xb4, 0x7e, 0x14, 0x2b, 0x6b,
	0x9d, 0x6d, 0x04, 0x0a, 0x54, 0x47, 0x61, 0x2c, 0x5f, 0x95, 0x93, 0x0e, 0x50, 0x4b, 0xa9, 0x85,
	0xc6, 0x8e, 0x50, 0x16, 0xba, 0xd1, 0x4c, 0x95, 0xad, 0x3a, 0x62, 0xc3, 0x0a, 0xc5, 0xc4, 0x29,
	0x28, 0xb1, 0xc6, 0xd2, 0x92, 0x9e, 0xa2, 0x98, 0x5e, 0x90, 0x38, 0xa8, 0x6c, 0xdf, 0x68, 0xdd,
	0x12, 0x82, 0x62, 0xa2, 0x1c, 0x1a, 0xaa, 0x33, 0x5d, 0xd3, 0x5b, 0x34, 0x6e, 0xb8, 0x1b, 0xc8,
	0xe9, 0x70, 0xca, 0xbd, 0xa7, 0x83, 0x26, 0x92, 0x06, 0x0a, 0x52, 0x38, 0x96, 0x1e, 0xa2, 0xaa,
	0xfe, 0xa7, 0x85, 0xca, 0x30, 0xf4, 0x87, 0x2a, 0x31, 0x72, 0x09, 0x6c, 0xe2, 0x22, 0x76, 0xcf,
	0xc8, 0x36, 0xd5, 0x5b, 0xed, 0x5d, 0xc5, 0x0c, 0x96, 0xe6, 0xc8, 0x39, 0xca, 0x8c, 0x07, 0x91,
	0xeb, 0x93, 0xa6, 0xe9, 0x5c, 0x87, 0xd4, 0xfa, 0x6f, 0xaa, 0x7f, 0x71, 0x29, 0xf0, 0x02, 0x15,
	0xf5, 0x11, 0xe9, 0x26, 0xf2, 0x50, 0xf2, 0x0c, 0xa5, 0x71, 0x16, 0x6e, 0x80, 0xe2, 0x58, 0x46,
	0x71, 0x06, 0x6c, 0xf4, 0x32, 0xcb, 0x30, 0xad, 0xa4, 0x77, 0x6a, 0x0f, 0xd7, 0xdc, 0xe5, 0x56,
	0xd8, 0x15, 0xfe, 0x19, 0xff, 0x79, 0x0f, 0xdc, 0x32, 0xd5, 0xed, 0xb5, 0xa0, 0xb9, 0x6b, 0xfb,
	0xfd, 0xbb, 0x93, 0xff, 0x50, 0xe7, 0x4b, 0x9d, 0xb7, 0x9f, 0x4e, 0xee, 0xa1, 0xac, 0x9f, 0xc9,
	0xc9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xcd, 0x30, 0x47, 0x3a, 0x03, 0x00, 0x00,
}
