// Code generated by protoc-gen-go.
// source: formic_api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	formic_api.proto

It has these top-level messages:
	DirEnt
	DirEntries
	Attr
	SetAttrRequest
	SetAttrResponse
	GetAttrRequest
	GetAttrResponse
	ReadRequest
	ReadResponse
	WriteRequest
	WriteResponse
	MkDirRequest
	MkDirResponse
	CreateRequest
	CreateResponse
	RemoveRequest
	RemoveResponse
	LookupRequest
	LookupResponse
	ReadDirAllRequest
	ReadDirAllResponse
	SymlinkRequest
	SymlinkResponse
	ReadlinkRequest
	ReadlinkResponse
	GetxattrRequest
	GetxattrResponse
	SetxattrRequest
	SetxattrResponse
	ListxattrRequest
	ListxattrResponse
	RemovexattrRequest
	RemovexattrResponse
	RenameRequest
	RenameResponse
	StatfsRequest
	StatfsResponse
	InodeEntry
	Tombstone
	DirEntry
	FileBlock
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

// DirEnt is a directory entry
type DirEnt struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Parent uint64 `protobuf:"varint,2,opt,name=parent" json:"parent,omitempty"`
	Attr   *Attr  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *DirEnt) Reset()                    { *m = DirEnt{} }
func (m *DirEnt) String() string            { return proto1.CompactTextString(m) }
func (*DirEnt) ProtoMessage()               {}
func (*DirEnt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DirEnt) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// DirEntries just contains a list of directory entries
type DirEntries struct {
	DirEntries  []*DirEnt `protobuf:"bytes,1,rep,name=DirEntries" json:"DirEntries,omitempty"`
	FileEntries []*DirEnt `protobuf:"bytes,2,rep,name=FileEntries" json:"FileEntries,omitempty"`
}

func (m *DirEntries) Reset()                    { *m = DirEntries{} }
func (m *DirEntries) String() string            { return proto1.CompactTextString(m) }
func (*DirEntries) ProtoMessage()               {}
func (*DirEntries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DirEntries) GetDirEntries() []*DirEnt {
	if m != nil {
		return m.DirEntries
	}
	return nil
}

func (m *DirEntries) GetFileEntries() []*DirEnt {
	if m != nil {
		return m.FileEntries
	}
	return nil
}

// Attr
type Attr struct {
	Inode  uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Atime  int64  `protobuf:"varint,2,opt,name=atime" json:"atime,omitempty"`
	Mtime  int64  `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	Ctime  int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime,omitempty"`
	Crtime int64  `protobuf:"varint,5,opt,name=crtime" json:"crtime,omitempty"`
	Mode   uint32 `protobuf:"varint,6,opt,name=mode" json:"mode,omitempty"`
	Valid  int32  `protobuf:"varint,7,opt,name=valid" json:"valid,omitempty"`
	Size   uint64 `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	Uid    uint32 `protobuf:"varint,9,opt,name=uid" json:"uid,omitempty"`
	Gid    uint32 `protobuf:"varint,10,opt,name=gid" json:"gid,omitempty"`
}

func (m *Attr) Reset()                    { *m = Attr{} }
func (m *Attr) String() string            { return proto1.CompactTextString(m) }
func (*Attr) ProtoMessage()               {}
func (*Attr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// SetAttrRequest
type SetAttrRequest struct {
	Attr  *Attr  `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
	Valid uint32 `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *SetAttrRequest) Reset()                    { *m = SetAttrRequest{} }
func (m *SetAttrRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetAttrRequest) ProtoMessage()               {}
func (*SetAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetAttrRequest) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// SetAttrResponse
type SetAttrResponse struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
}

func (m *SetAttrResponse) Reset()                    { *m = SetAttrResponse{} }
func (m *SetAttrResponse) String() string            { return proto1.CompactTextString(m) }
func (*SetAttrResponse) ProtoMessage()               {}
func (*SetAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetAttrResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// GetAttrRequest
type GetAttrRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
}

func (m *GetAttrRequest) Reset()                    { *m = GetAttrRequest{} }
func (m *GetAttrRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAttrRequest) ProtoMessage()               {}
func (*GetAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// GetAttrResponse
type GetAttrResponse struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
}

func (m *GetAttrResponse) Reset()                    { *m = GetAttrResponse{} }
func (m *GetAttrResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetAttrResponse) ProtoMessage()               {}
func (*GetAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAttrResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// ReqadRequest
type ReadRequest struct {
	Inode  uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Size   int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// ReadResponse
type ReadResponse struct {
	Inode   uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// WriteRequest
type WriteRequest struct {
	Inode   uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Offset  int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto1.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// WriteResponse place holder. Maybe use an enum so
// we can map to fuse errors ?
type WriteResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto1.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// MkdirRequest
type MkDirRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr   *Attr  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *MkDirRequest) Reset()                    { *m = MkDirRequest{} }
func (m *MkDirRequest) String() string            { return proto1.CompactTextString(m) }
func (*MkDirRequest) ProtoMessage()               {}
func (*MkDirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MkDirRequest) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// MkdirResponse
type MkDirResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attr *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *MkDirResponse) Reset()                    { *m = MkDirResponse{} }
func (m *MkDirResponse) String() string            { return proto1.CompactTextString(m) }
func (*MkDirResponse) ProtoMessage()               {}
func (*MkDirResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MkDirResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// CreateRequest
type CreateRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr   *Attr  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CreateRequest) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// CreateResponse
type CreateResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attr *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// RemoveRequest
type RemoveRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto1.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

// RemoveResponse
type RemoveResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto1.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// LookupRequest
type LookupRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *LookupRequest) Reset()                    { *m = LookupRequest{} }
func (m *LookupRequest) String() string            { return proto1.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()               {}
func (*LookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// LookupResponse is a directory entry
type LookupResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Attr *Attr  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *LookupResponse) Reset()                    { *m = LookupResponse{} }
func (m *LookupResponse) String() string            { return proto1.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()               {}
func (*LookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *LookupResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// ReadDirAllRequest
type ReadDirAllRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
}

func (m *ReadDirAllRequest) Reset()                    { *m = ReadDirAllRequest{} }
func (m *ReadDirAllRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadDirAllRequest) ProtoMessage()               {}
func (*ReadDirAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

// ReadDirAllResponse
type ReadDirAllResponse struct {
	DirEntries  []*DirEnt `protobuf:"bytes,1,rep,name=DirEntries" json:"DirEntries,omitempty"`
	FileEntries []*DirEnt `protobuf:"bytes,2,rep,name=FileEntries" json:"FileEntries,omitempty"`
}

func (m *ReadDirAllResponse) Reset()                    { *m = ReadDirAllResponse{} }
func (m *ReadDirAllResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadDirAllResponse) ProtoMessage()               {}
func (*ReadDirAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ReadDirAllResponse) GetDirEntries() []*DirEnt {
	if m != nil {
		return m.DirEntries
	}
	return nil
}

func (m *ReadDirAllResponse) GetFileEntries() []*DirEnt {
	if m != nil {
		return m.FileEntries
	}
	return nil
}

// SymlinkRequest
type SymlinkRequest struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Target string `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Uid    uint32 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	Gid    uint32 `protobuf:"varint,5,opt,name=gid" json:"gid,omitempty"`
}

func (m *SymlinkRequest) Reset()                    { *m = SymlinkRequest{} }
func (m *SymlinkRequest) String() string            { return proto1.CompactTextString(m) }
func (*SymlinkRequest) ProtoMessage()               {}
func (*SymlinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// SymlinkResponse
type SymlinkResponse struct {
	Parent uint64 `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr   *Attr  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *SymlinkResponse) Reset()                    { *m = SymlinkResponse{} }
func (m *SymlinkResponse) String() string            { return proto1.CompactTextString(m) }
func (*SymlinkResponse) ProtoMessage()               {}
func (*SymlinkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SymlinkResponse) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

// ReadlinkRequest
type ReadlinkRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
}

func (m *ReadlinkRequest) Reset()                    { *m = ReadlinkRequest{} }
func (m *ReadlinkRequest) String() string            { return proto1.CompactTextString(m) }
func (*ReadlinkRequest) ProtoMessage()               {}
func (*ReadlinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

// ReadlinkResponse
type ReadlinkResponse struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
}

func (m *ReadlinkResponse) Reset()                    { *m = ReadlinkResponse{} }
func (m *ReadlinkResponse) String() string            { return proto1.CompactTextString(m) }
func (*ReadlinkResponse) ProtoMessage()               {}
func (*ReadlinkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

// Getxattr
type GetxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Size     uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Position uint32 `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
}

func (m *GetxattrRequest) Reset()                    { *m = GetxattrRequest{} }
func (m *GetxattrRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetxattrRequest) ProtoMessage()               {}
func (*GetxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type GetxattrResponse struct {
	Xattr []byte `protobuf:"bytes,1,opt,name=xattr,proto3" json:"xattr,omitempty"`
}

func (m *GetxattrResponse) Reset()                    { *m = GetxattrResponse{} }
func (m *GetxattrResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetxattrResponse) ProtoMessage()               {}
func (*GetxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

// Setxattr
type SetxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Position uint32 `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	Flags    uint32 `protobuf:"varint,5,opt,name=flags" json:"flags,omitempty"`
}

func (m *SetxattrRequest) Reset()                    { *m = SetxattrRequest{} }
func (m *SetxattrRequest) String() string            { return proto1.CompactTextString(m) }
func (*SetxattrRequest) ProtoMessage()               {}
func (*SetxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type SetxattrResponse struct {
}

func (m *SetxattrResponse) Reset()                    { *m = SetxattrResponse{} }
func (m *SetxattrResponse) String() string            { return proto1.CompactTextString(m) }
func (*SetxattrResponse) ProtoMessage()               {}
func (*SetxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

// Listxattr
type ListxattrRequest struct {
	Inode    uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Size     uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Position uint32 `protobuf:"varint,3,opt,name=position" json:"position,omitempty"`
}

func (m *ListxattrRequest) Reset()                    { *m = ListxattrRequest{} }
func (m *ListxattrRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListxattrRequest) ProtoMessage()               {}
func (*ListxattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type ListxattrResponse struct {
	Xattr []byte `protobuf:"bytes,1,opt,name=xattr,proto3" json:"xattr,omitempty"`
}

func (m *ListxattrResponse) Reset()                    { *m = ListxattrResponse{} }
func (m *ListxattrResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListxattrResponse) ProtoMessage()               {}
func (*ListxattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

// Removexattr
type RemovexattrRequest struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RemovexattrRequest) Reset()                    { *m = RemovexattrRequest{} }
func (m *RemovexattrRequest) String() string            { return proto1.CompactTextString(m) }
func (*RemovexattrRequest) ProtoMessage()               {}
func (*RemovexattrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type RemovexattrResponse struct {
}

func (m *RemovexattrResponse) Reset()                    { *m = RemovexattrResponse{} }
func (m *RemovexattrResponse) String() string            { return proto1.CompactTextString(m) }
func (*RemovexattrResponse) ProtoMessage()               {}
func (*RemovexattrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

// Rename
type RenameRequest struct {
	OldParent uint64 `protobuf:"varint,1,opt,name=oldParent" json:"oldParent,omitempty"`
	NewParent uint64 `protobuf:"varint,2,opt,name=newParent" json:"newParent,omitempty"`
	OldName   string `protobuf:"bytes,3,opt,name=oldName" json:"oldName,omitempty"`
	NewName   string `protobuf:"bytes,4,opt,name=newName" json:"newName,omitempty"`
}

func (m *RenameRequest) Reset()                    { *m = RenameRequest{} }
func (m *RenameRequest) String() string            { return proto1.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()               {}
func (*RenameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type RenameResponse struct {
}

func (m *RenameResponse) Reset()                    { *m = RenameResponse{} }
func (m *RenameResponse) String() string            { return proto1.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()               {}
func (*RenameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

// Statfs
type StatfsRequest struct {
}

func (m *StatfsRequest) Reset()                    { *m = StatfsRequest{} }
func (m *StatfsRequest) String() string            { return proto1.CompactTextString(m) }
func (*StatfsRequest) ProtoMessage()               {}
func (*StatfsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type StatfsResponse struct {
	Blocks  uint64 `protobuf:"varint,1,opt,name=blocks" json:"blocks,omitempty"`
	Bfree   uint64 `protobuf:"varint,2,opt,name=bfree" json:"bfree,omitempty"`
	Bavail  uint64 `protobuf:"varint,3,opt,name=bavail" json:"bavail,omitempty"`
	Files   uint64 `protobuf:"varint,4,opt,name=files" json:"files,omitempty"`
	Ffree   uint64 `protobuf:"varint,5,opt,name=ffree" json:"ffree,omitempty"`
	Bsize   uint32 `protobuf:"varint,6,opt,name=bsize" json:"bsize,omitempty"`
	Namelen uint32 `protobuf:"varint,7,opt,name=namelen" json:"namelen,omitempty"`
	Frsize  uint32 `protobuf:"varint,8,opt,name=frsize" json:"frsize,omitempty"`
}

func (m *StatfsResponse) Reset()                    { *m = StatfsResponse{} }
func (m *StatfsResponse) String() string            { return proto1.CompactTextString(m) }
func (*StatfsResponse) ProtoMessage()               {}
func (*StatfsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

// Inode
// This is used for serialization of the inode metadata
// This is *not* used for api calls
type InodeEntry struct {
	Version   uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	IsDir     bool              `protobuf:"varint,2,opt,name=isDir" json:"isDir,omitempty"`
	Attr      *Attr             `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
	Parent    uint64            `protobuf:"varint,4,opt,name=parent" json:"parent,omitempty"`
	Inode     uint64            `protobuf:"varint,5,opt,name=inode" json:"inode,omitempty"`
	NodeCount uint64            `protobuf:"varint,6,opt,name=nodeCount" json:"nodeCount,omitempty"`
	IsLink    bool              `protobuf:"varint,7,opt,name=isLink" json:"isLink,omitempty"`
	Target    string            `protobuf:"bytes,8,opt,name=target" json:"target,omitempty"`
	Xattr     map[string][]byte `protobuf:"bytes,9,rep,name=xattr" json:"xattr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Blocks    uint64            `protobuf:"varint,10,opt,name=blocks" json:"blocks,omitempty"`
	BlockSize uint64            `protobuf:"varint,11,opt,name=blockSize" json:"blockSize,omitempty"`
	LastBlock uint64            `protobuf:"varint,12,opt,name=lastBlock" json:"lastBlock,omitempty"`
	FsId      []byte            `protobuf:"bytes,13,opt,name=fsId,proto3" json:"fsId,omitempty"`
}

func (m *InodeEntry) Reset()                    { *m = InodeEntry{} }
func (m *InodeEntry) String() string            { return proto1.CompactTextString(m) }
func (*InodeEntry) ProtoMessage()               {}
func (*InodeEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *InodeEntry) GetAttr() *Attr {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *InodeEntry) GetXattr() map[string][]byte {
	if m != nil {
		return m.Xattr
	}
	return nil
}

// Tombstone
// Stores information needed to keep track of deleted items
type Tombstone struct {
	Dtime  int64  `protobuf:"varint,1,opt,name=dtime" json:"dtime,omitempty"`
	Qtime  int64  `protobuf:"varint,2,opt,name=qtime" json:"qtime,omitempty"`
	FsId   []byte `protobuf:"bytes,3,opt,name=fsId,proto3" json:"fsId,omitempty"`
	Inode  uint64 `protobuf:"varint,4,opt,name=inode" json:"inode,omitempty"`
	Blocks uint64 `protobuf:"varint,5,opt,name=blocks" json:"blocks,omitempty"`
}

func (m *Tombstone) Reset()                    { *m = Tombstone{} }
func (m *Tombstone) String() string            { return proto1.CompactTextString(m) }
func (*Tombstone) ProtoMessage()               {}
func (*Tombstone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

// DirEntry
// This is used for the serialization of dir info in the group score
// This is *not* used for api calls
type DirEntry struct {
	Version   uint32     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id        []byte     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Tombstone *Tombstone `protobuf:"bytes,4,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *DirEntry) Reset()                    { *m = DirEntry{} }
func (m *DirEntry) String() string            { return proto1.CompactTextString(m) }
func (*DirEntry) ProtoMessage()               {}
func (*DirEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *DirEntry) GetTombstone() *Tombstone {
	if m != nil {
		return m.Tombstone
	}
	return nil
}

// FileBlock
// This is used for storing blocks in value store
// This is *not* used for api calls
type FileBlock struct {
	Version  uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum uint32 `protobuf:"varint,3,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *FileBlock) Reset()                    { *m = FileBlock{} }
func (m *FileBlock) String() string            { return proto1.CompactTextString(m) }
func (*FileBlock) ProtoMessage()               {}
func (*FileBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func init() {
	proto1.RegisterType((*DirEnt)(nil), "proto.DirEnt")
	proto1.RegisterType((*DirEntries)(nil), "proto.DirEntries")
	proto1.RegisterType((*Attr)(nil), "proto.Attr")
	proto1.RegisterType((*SetAttrRequest)(nil), "proto.SetAttrRequest")
	proto1.RegisterType((*SetAttrResponse)(nil), "proto.SetAttrResponse")
	proto1.RegisterType((*GetAttrRequest)(nil), "proto.GetAttrRequest")
	proto1.RegisterType((*GetAttrResponse)(nil), "proto.GetAttrResponse")
	proto1.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto1.RegisterType((*ReadResponse)(nil), "proto.ReadResponse")
	proto1.RegisterType((*WriteRequest)(nil), "proto.WriteRequest")
	proto1.RegisterType((*WriteResponse)(nil), "proto.WriteResponse")
	proto1.RegisterType((*MkDirRequest)(nil), "proto.MkDirRequest")
	proto1.RegisterType((*MkDirResponse)(nil), "proto.MkDirResponse")
	proto1.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto1.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
	proto1.RegisterType((*RemoveRequest)(nil), "proto.RemoveRequest")
	proto1.RegisterType((*RemoveResponse)(nil), "proto.RemoveResponse")
	proto1.RegisterType((*LookupRequest)(nil), "proto.LookupRequest")
	proto1.RegisterType((*LookupResponse)(nil), "proto.LookupResponse")
	proto1.RegisterType((*ReadDirAllRequest)(nil), "proto.ReadDirAllRequest")
	proto1.RegisterType((*ReadDirAllResponse)(nil), "proto.ReadDirAllResponse")
	proto1.RegisterType((*SymlinkRequest)(nil), "proto.SymlinkRequest")
	proto1.RegisterType((*SymlinkResponse)(nil), "proto.SymlinkResponse")
	proto1.RegisterType((*ReadlinkRequest)(nil), "proto.ReadlinkRequest")
	proto1.RegisterType((*ReadlinkResponse)(nil), "proto.ReadlinkResponse")
	proto1.RegisterType((*GetxattrRequest)(nil), "proto.GetxattrRequest")
	proto1.RegisterType((*GetxattrResponse)(nil), "proto.GetxattrResponse")
	proto1.RegisterType((*SetxattrRequest)(nil), "proto.SetxattrRequest")
	proto1.RegisterType((*SetxattrResponse)(nil), "proto.SetxattrResponse")
	proto1.RegisterType((*ListxattrRequest)(nil), "proto.ListxattrRequest")
	proto1.RegisterType((*ListxattrResponse)(nil), "proto.ListxattrResponse")
	proto1.RegisterType((*RemovexattrRequest)(nil), "proto.RemovexattrRequest")
	proto1.RegisterType((*RemovexattrResponse)(nil), "proto.RemovexattrResponse")
	proto1.RegisterType((*RenameRequest)(nil), "proto.RenameRequest")
	proto1.RegisterType((*RenameResponse)(nil), "proto.RenameResponse")
	proto1.RegisterType((*StatfsRequest)(nil), "proto.StatfsRequest")
	proto1.RegisterType((*StatfsResponse)(nil), "proto.StatfsResponse")
	proto1.RegisterType((*InodeEntry)(nil), "proto.InodeEntry")
	proto1.RegisterType((*Tombstone)(nil), "proto.Tombstone")
	proto1.RegisterType((*DirEntry)(nil), "proto.DirEntry")
	proto1.RegisterType((*FileBlock)(nil), "proto.FileBlock")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Api service

type ApiClient interface {
	SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error)
	GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	MkDir(ctx context.Context, in *MkDirRequest, opts ...grpc.CallOption) (*MkDirResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	ReadDirAll(ctx context.Context, in *ReadDirAllRequest, opts ...grpc.CallOption) (*ReadDirAllResponse, error)
	Symlink(ctx context.Context, in *SymlinkRequest, opts ...grpc.CallOption) (*SymlinkResponse, error)
	Readlink(ctx context.Context, in *ReadlinkRequest, opts ...grpc.CallOption) (*ReadlinkResponse, error)
	Getxattr(ctx context.Context, in *GetxattrRequest, opts ...grpc.CallOption) (*GetxattrResponse, error)
	Setxattr(ctx context.Context, in *SetxattrRequest, opts ...grpc.CallOption) (*SetxattrResponse, error)
	Listxattr(ctx context.Context, in *ListxattrRequest, opts ...grpc.CallOption) (*ListxattrResponse, error)
	Removexattr(ctx context.Context, in *RemovexattrRequest, opts ...grpc.CallOption) (*RemovexattrResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	Statfs(ctx context.Context, in *StatfsRequest, opts ...grpc.CallOption) (*StatfsResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) SetAttr(ctx context.Context, in *SetAttrRequest, opts ...grpc.CallOption) (*SetAttrResponse, error) {
	out := new(SetAttrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/SetAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrResponse, error) {
	out := new(GetAttrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/GetAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) MkDir(ctx context.Context, in *MkDirRequest, opts ...grpc.CallOption) (*MkDirResponse, error) {
	out := new(MkDirResponse)
	err := grpc.Invoke(ctx, "/proto.Api/MkDir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ReadDirAll(ctx context.Context, in *ReadDirAllRequest, opts ...grpc.CallOption) (*ReadDirAllResponse, error) {
	out := new(ReadDirAllResponse)
	err := grpc.Invoke(ctx, "/proto.Api/ReadDirAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Symlink(ctx context.Context, in *SymlinkRequest, opts ...grpc.CallOption) (*SymlinkResponse, error) {
	out := new(SymlinkResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Symlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Readlink(ctx context.Context, in *ReadlinkRequest, opts ...grpc.CallOption) (*ReadlinkResponse, error) {
	out := new(ReadlinkResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Readlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Getxattr(ctx context.Context, in *GetxattrRequest, opts ...grpc.CallOption) (*GetxattrResponse, error) {
	out := new(GetxattrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Getxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Setxattr(ctx context.Context, in *SetxattrRequest, opts ...grpc.CallOption) (*SetxattrResponse, error) {
	out := new(SetxattrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Setxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Listxattr(ctx context.Context, in *ListxattrRequest, opts ...grpc.CallOption) (*ListxattrResponse, error) {
	out := new(ListxattrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Listxattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Removexattr(ctx context.Context, in *RemovexattrRequest, opts ...grpc.CallOption) (*RemovexattrResponse, error) {
	out := new(RemovexattrResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Removexattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	out := new(RenameResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Rename", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Statfs(ctx context.Context, in *StatfsRequest, opts ...grpc.CallOption) (*StatfsResponse, error) {
	out := new(StatfsResponse)
	err := grpc.Invoke(ctx, "/proto.Api/Statfs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	SetAttr(context.Context, *SetAttrRequest) (*SetAttrResponse, error)
	GetAttr(context.Context, *GetAttrRequest) (*GetAttrResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	MkDir(context.Context, *MkDirRequest) (*MkDirResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	ReadDirAll(context.Context, *ReadDirAllRequest) (*ReadDirAllResponse, error)
	Symlink(context.Context, *SymlinkRequest) (*SymlinkResponse, error)
	Readlink(context.Context, *ReadlinkRequest) (*ReadlinkResponse, error)
	Getxattr(context.Context, *GetxattrRequest) (*GetxattrResponse, error)
	Setxattr(context.Context, *SetxattrRequest) (*SetxattrResponse, error)
	Listxattr(context.Context, *ListxattrRequest) (*ListxattrResponse, error)
	Removexattr(context.Context, *RemovexattrRequest) (*RemovexattrResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	Statfs(context.Context, *StatfsRequest) (*StatfsResponse, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_SetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).SetAttr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_GetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).GetAttr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Read(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Write(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_MkDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MkDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).MkDir(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Remove(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Lookup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_ReadDirAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ReadDirAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).ReadDirAll(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Symlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SymlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Symlink(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Readlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ReadlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Readlink(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Getxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Getxattr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Setxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SetxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Setxattr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Listxattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListxattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Listxattr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Removexattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RemovexattrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Removexattr(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Rename(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Api_Statfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ApiServer).Statfs(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAttr",
			Handler:    _Api_SetAttr_Handler,
		},
		{
			MethodName: "GetAttr",
			Handler:    _Api_GetAttr_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Api_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Api_Write_Handler,
		},
		{
			MethodName: "MkDir",
			Handler:    _Api_MkDir_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Api_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Api_Remove_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Api_Lookup_Handler,
		},
		{
			MethodName: "ReadDirAll",
			Handler:    _Api_ReadDirAll_Handler,
		},
		{
			MethodName: "Symlink",
			Handler:    _Api_Symlink_Handler,
		},
		{
			MethodName: "Readlink",
			Handler:    _Api_Readlink_Handler,
		},
		{
			MethodName: "Getxattr",
			Handler:    _Api_Getxattr_Handler,
		},
		{
			MethodName: "Setxattr",
			Handler:    _Api_Setxattr_Handler,
		},
		{
			MethodName: "Listxattr",
			Handler:    _Api_Listxattr_Handler,
		},
		{
			MethodName: "Removexattr",
			Handler:    _Api_Removexattr_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Api_Rename_Handler,
		},
		{
			MethodName: "Statfs",
			Handler:    _Api_Statfs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 1213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xae, 0x5f, 0x63, 0x8f, 0x7d, 0x89, 0x7b, 0x25, 0xc5, 0xb1, 0x90, 0x9a, 0x2e, 0x5f, 0x90,
	0x28, 0x91, 0x1a, 0x90, 0x28, 0x11, 0x20, 0x42, 0xa0, 0xa6, 0x28, 0x54, 0x55, 0x8c, 0x68, 0x05,
	0x12, 0x68, 0x13, 0xaf, 0xc3, 0x29, 0x67, 0x9f, 0x7b, 0x77, 0x0e, 0x0d, 0xdf, 0xf8, 0x01, 0x7c,
	0xe6, 0xaf, 0xf0, 0xf3, 0x98, 0x9d, 0x7d, 0xb9, 0xdd, 0xb3, 0x13, 0xdc, 0xaa, 0x9f, 0xac, 0xd9,
	0x9d, 0x67, 0x9e, 0xd9, 0xb9, 0x79, 0x33, 0xf4, 0x26, 0x49, 0x3a, 0x8d, 0xce, 0x7e, 0xe3, 0xf3,
	0x68, 0x6f, 0x9e, 0x26, 0x79, 0x12, 0x36, 0xe8, 0x87, 0x1d, 0x42, 0xf3, 0x9b, 0x28, 0xfd, 0x76,
	0x96, 0x87, 0x5d, 0xa8, 0xcf, 0xf8, 0x54, 0xf4, 0x2b, 0xbb, 0x95, 0x0f, 0xda, 0xe1, 0x26, 0x34,
	0xe7, 0x3c, 0x15, 0xb3, 0xbc, 0x5f, 0x45, 0xb9, 0x1e, 0xee, 0x40, 0x9d, 0xe7, 0x79, 0xda, 0xaf,
	0xa1, 0xd4, 0xd9, 0xef, 0x28, 0x23, 0x7b, 0x87, 0x78, 0xc4, 0x46, 0x00, 0xca, 0x44, 0x1a, 0x89,
	0x2c, 0xbc, 0xef, 0x4a, 0x68, 0xac, 0x86, 0xea, 0x81, 0x56, 0xd7, 0x4c, 0x0c, 0x3a, 0x8f, 0xa3,
	0x58, 0x18, 0x9d, 0xea, 0x0a, 0x1d, 0xf6, 0x4f, 0x05, 0xea, 0xd2, 0x7a, 0x18, 0x40, 0x23, 0x9a,
	0x25, 0x63, 0xe5, 0x57, 0x5d, 0x8a, 0x3c, 0x8f, 0xd0, 0x4d, 0xe9, 0x56, 0x4d, 0x8a, 0x53, 0x12,
	0x6b, 0x46, 0x3c, 0x23, 0xb1, 0x4e, 0x22, 0x3e, 0xe2, 0x2c, 0x25, 0xb9, 0x41, 0x32, 0x3e, 0x71,
	0x2a, 0x4d, 0x35, 0x51, 0x0a, 0xa4, 0xf2, 0x25, 0x8f, 0xa3, 0x71, 0x7f, 0x03, 0xc5, 0x86, 0xbc,
	0xcc, 0xa2, 0x3f, 0x45, 0xbf, 0x45, 0x3c, 0x1d, 0xa8, 0x2d, 0xf0, 0xaa, 0x4d, 0x9a, 0x28, 0x9c,
	0xa3, 0x00, 0x52, 0x60, 0x07, 0xb0, 0x39, 0x12, 0xb9, 0xf4, 0xed, 0x44, 0xbc, 0x5c, 0x88, 0x2c,
	0xb7, 0xb1, 0xa9, 0x2c, 0xc5, 0xa6, 0xe0, 0xa8, 0x12, 0xf6, 0x01, 0x6c, 0x59, 0x6c, 0x36, 0x4f,
	0x66, 0x99, 0xb8, 0x01, 0xcc, 0xee, 0xc1, 0xe6, 0xd0, 0x67, 0xf2, 0x83, 0x21, 0xcd, 0x0d, 0xd7,
	0x37, 0x77, 0x00, 0x9d, 0x13, 0xc1, 0xc7, 0xab, 0x6d, 0xc9, 0x58, 0x25, 0x93, 0x49, 0x26, 0x72,
	0x1d, 0x59, 0x13, 0x0e, 0x0a, 0x2c, 0xdb, 0x83, 0xae, 0xc2, 0x6a, 0x9a, 0x12, 0x78, 0x0b, 0x36,
	0xe6, 0xfc, 0x2a, 0x4e, 0xb8, 0x7a, 0x68, 0x97, 0x7d, 0x09, 0xdd, 0xe7, 0x69, 0x94, 0x8b, 0x35,
	0xc9, 0x1c, 0x7c, 0x8d, 0xf0, 0xf7, 0x20, 0xd0, 0x78, 0x4d, 0x88, 0x88, 0x2c, 0xe7, 0xf9, 0x22,
	0x23, 0x0b, 0x0d, 0x36, 0x84, 0xee, 0x0f, 0x17, 0x98, 0x2b, 0x86, 0xa0, 0xc8, 0x57, 0xc5, 0x60,
	0xb2, 0xb9, 0x4a, 0xd9, 0x7c, 0x43, 0xf6, 0x3e, 0x82, 0x40, 0x1b, 0xd2, 0x4c, 0x7e, 0x1d, 0x18,
	0x64, 0x75, 0x19, 0xf9, 0x1d, 0x04, 0x47, 0xa9, 0xe0, 0xc5, 0x23, 0xdf, 0xd8, 0x87, 0xcf, 0x60,
	0xd3, 0x58, 0x7a, 0x5d, 0x27, 0x3e, 0x82, 0xe0, 0x44, 0x4c, 0x93, 0xcb, 0xf5, 0x9c, 0x60, 0xbb,
	0xb0, 0x69, 0xd4, 0xaf, 0x09, 0x2c, 0x1a, 0x3c, 0x4e, 0x92, 0x8b, 0xc5, 0x7c, 0x3d, 0x83, 0xe8,
	0xba, 0x51, 0x7f, 0x5d, 0xd7, 0x19, 0xdc, 0x96, 0x39, 0x85, 0xb1, 0x3f, 0x8c, 0xe3, 0x6b, 0x32,
	0xfc, 0x17, 0x08, 0x5d, 0x1d, 0x4d, 0xf1, 0x96, 0x7a, 0xcc, 0x0b, 0xac, 0xe4, 0xab, 0x69, 0x1c,
	0xcd, 0x2e, 0xd6, 0xfb, 0x82, 0x78, 0x9b, 0xf3, 0xf4, 0x1c, 0xb3, 0xb6, 0x46, 0xb2, 0xee, 0x11,
	0x75, 0xb7, 0x47, 0x34, 0xa8, 0xce, 0xbf, 0xc7, 0x3a, 0x37, 0x96, 0x8b, 0x38, 0xbf, 0x59, 0x72,
	0xec, 0xc2, 0x96, 0x0c, 0x81, 0xeb, 0x66, 0x29, 0x48, 0x0c, 0x7a, 0x85, 0x46, 0x41, 0xa7, 0x7d,
	0xa5, 0xef, 0xc0, 0x9e, 0x52, 0xab, 0x78, 0xc5, 0xaf, 0x6d, 0x26, 0x25, 0x87, 0xdc, 0xf2, 0x0f,
	0xc2, 0x1e, 0xb4, 0xe6, 0x49, 0x16, 0xe5, 0x51, 0x32, 0x53, 0xcf, 0x65, 0xf7, 0xa1, 0x57, 0xd8,
	0x2b, 0x9a, 0xc2, 0x2b, 0xdb, 0x7c, 0xba, 0xec, 0x57, 0x6a, 0x76, 0xeb, 0x53, 0xaa, 0x5e, 0xb9,
	0x50, 0x9c, 0xdd, 0x65, 0x4e, 0xa9, 0x30, 0x89, 0xf9, 0x79, 0xa6, 0x83, 0x1c, 0x42, 0x6f, 0x54,
	0x72, 0x01, 0xc7, 0x59, 0xef, 0x38, 0xca, 0xfe, 0x8f, 0x94, 0x5e, 0x56, 0x5d, 0x7a, 0x19, 0xbd,
	0x55, 0xa6, 0xa5, 0x63, 0x62, 0xf5, 0xd3, 0x1e, 0xca, 0xb4, 0x94, 0x65, 0xb4, 0xf6, 0xeb, 0xd8,
	0x36, 0xdc, 0xf1, 0x20, 0xda, 0xe1, 0xe7, 0xb2, 0x7e, 0xa5, 0x9a, 0x31, 0x72, 0x1b, 0xda, 0x49,
	0x3c, 0x7e, 0xe6, 0xa6, 0x0a, 0x1e, 0xcd, 0xc4, 0x1f, 0xcf, 0xdc, 0x71, 0x8c, 0x0d, 0x13, 0xb5,
	0x9e, 0x72, 0x3d, 0xf9, 0xda, 0xf2, 0x00, 0x75, 0xe8, 0xa0, 0x4e, 0x7c, 0x3d, 0x59, 0xe9, 0xca,
	0xb0, 0xa6, 0xda, 0x82, 0x60, 0x84, 0x95, 0x3e, 0xc9, 0x34, 0x15, 0xfb, 0xbb, 0x82, 0x05, 0xa0,
	0x4f, 0x8a, 0xb4, 0x39, 0x8d, 0x93, 0xb3, 0x8b, 0xac, 0x18, 0xb7, 0xa7, 0x93, 0x54, 0x08, 0x4d,
	0x2b, 0xaf, 0xf9, 0x25, 0x8f, 0x62, 0x62, 0xa5, 0xeb, 0x09, 0x56, 0x59, 0x46, 0x9c, 0x4a, 0x24,
	0xed, 0x86, 0x05, 0x53, 0xa8, 0xd5, 0xbc, 0x95, 0x2e, 0xa2, 0x3f, 0xb1, 0x98, 0xd1, 0xc4, 0x0d,
	0xa4, 0xb5, 0x49, 0x6a, 0x67, 0x6e, 0xc0, 0xfe, 0xad, 0x02, 0x3c, 0x91, 0x01, 0x94, 0x55, 0x7b,
	0x25, 0xf5, 0x2f, 0x05, 0xde, 0xe3, 0x97, 0xa9, 0x98, 0xef, 0x1f, 0x65, 0x58, 0xbb, 0xe4, 0x4c,
	0xeb, 0x86, 0x9a, 0x71, 0x8a, 0xcd, 0x3a, 0xa6, 0xbe, 0x4c, 0xc3, 0x06, 0x14, 0xa5, 0xa3, 0x64,
	0x81, 0x1a, 0x4d, 0xf3, 0xb2, 0x28, 0x3b, 0xc6, 0x0a, 0x22, 0xdf, 0x5a, 0x4e, 0xfd, 0xb4, 0x28,
	0xbe, 0x1f, 0x9a, 0x04, 0x68, 0x53, 0x27, 0x79, 0x4f, 0xb3, 0x15, 0xee, 0xee, 0xbd, 0x90, 0xd7,
	0xca, 0xf3, 0x22, 0x8a, 0x60, 0xf8, 0x48, 0x1e, 0xc9, 0xb7, 0x76, 0xcc, 0x51, 0xcc, 0xb3, 0xfc,
	0x6b, 0x79, 0xdc, 0xef, 0x9a, 0x7c, 0x99, 0x64, 0x4f, 0xc6, 0xfd, 0x40, 0xa6, 0xd8, 0xe0, 0x01,
	0x80, 0x63, 0x11, 0xbb, 0xcb, 0x85, 0xb8, 0xd2, 0x3d, 0xd5, 0x16, 0x0a, 0xcd, 0xda, 0x83, 0xea,
	0xa3, 0x0a, 0xfb, 0x09, 0xda, 0x3f, 0x26, 0xd3, 0xd3, 0x2c, 0x4f, 0x66, 0x94, 0xac, 0x63, 0xda,
	0x7a, 0x2a, 0x66, 0x29, 0x7a, 0xe9, 0xac, 0x4c, 0x86, 0x46, 0x55, 0x99, 0x8d, 0x4c, 0xdd, 0x7e,
	0x60, 0xe5, 0x39, 0x45, 0x8a, 0xfd, 0x0c, 0x2d, 0xdd, 0x69, 0x57, 0x7c, 0x0f, 0xbf, 0x7c, 0x01,
	0xaa, 0x91, 0xb1, 0xfa, 0x3e, 0xb4, 0x73, 0xe3, 0x0e, 0x59, 0xee, 0xec, 0xf7, 0x74, 0xc4, 0xac,
	0x9b, 0xec, 0x73, 0x68, 0xcb, 0x16, 0x4d, 0x21, 0x58, 0x69, 0x7c, 0xcc, 0x73, 0xae, 0xde, 0x28,
	0xcb, 0xf4, 0xec, 0x77, 0x81, 0x7e, 0x2d, 0xa6, 0xaa, 0x4c, 0xf7, 0xff, 0x6a, 0x41, 0xed, 0x70,
	0x1e, 0x85, 0x07, 0xb0, 0xa1, 0x57, 0xaa, 0x70, 0x5b, 0x53, 0xf8, 0xeb, 0xd9, 0xe0, 0x6e, 0xf9,
	0x58, 0xd7, 0xc3, 0x2d, 0x89, 0x1d, 0x96, 0xb0, 0xc3, 0xd5, 0xd8, 0xe1, 0x12, 0xf6, 0x21, 0xd4,
	0x65, 0xd3, 0x0d, 0x43, 0xad, 0xe1, 0xac, 0x56, 0x83, 0x3b, 0xde, 0x99, 0x85, 0x7c, 0x02, 0x0d,
	0x5a, 0x6a, 0x42, 0x73, 0xef, 0xae, 0x48, 0x83, 0x77, 0xfc, 0x43, 0x17, 0x45, 0x0b, 0x8a, 0x45,
	0xb9, 0x7b, 0x8f, 0x45, 0x79, 0x3b, 0x0c, 0xa2, 0x3e, 0x85, 0xa6, 0x5a, 0x29, 0x42, 0xa3, 0xe1,
	0xed, 0x2a, 0x83, 0xed, 0xd2, 0xa9, 0x0b, 0x54, 0x7d, 0xca, 0x02, 0xbd, 0xfd, 0xc2, 0x02, 0xfd,
	0x35, 0x42, 0x01, 0xd5, 0x26, 0x60, 0x81, 0xde, 0x1e, 0x61, 0x81, 0xfe, 0xba, 0x80, 0xc0, 0x23,
	0x80, 0x62, 0xc6, 0x87, 0x7d, 0x27, 0x76, 0xde, 0x6a, 0x30, 0xd8, 0x59, 0x71, 0xe3, 0x7e, 0x4a,
	0x3d, 0x71, 0x8b, 0x34, 0xf0, 0x66, 0x7b, 0x91, 0x06, 0xfe, 0x60, 0x46, 0xec, 0x17, 0xd0, 0x32,
	0xf3, 0x33, 0xbc, 0xeb, 0x90, 0xb8, 0xe8, 0x77, 0x97, 0xce, 0x5d, 0xb8, 0x19, 0x85, 0xa1, 0x93,
	0x2f, 0xee, 0x68, 0xb0, 0xf0, 0xf2, 0xcc, 0x54, 0xf0, 0x51, 0x19, 0x3e, 0xba, 0x06, 0x3e, 0x5a,
	0x86, 0x7f, 0x05, 0x6d, 0x3b, 0xae, 0x42, 0xa3, 0x57, 0x9e, 0x81, 0x83, 0xfe, 0xf2, 0x85, 0xb5,
	0xf0, 0x58, 0xfe, 0x2f, 0xb0, 0x93, 0x29, 0xdc, 0xf1, 0x3e, 0xb0, 0x67, 0x65, 0xb0, 0xea, 0xca,
	0xcf, 0x1c, 0xd9, 0x10, 0x9c, 0xcc, 0x71, 0x26, 0x9b, 0x93, 0x39, 0xde, 0x58, 0x22, 0xa0, 0x1a,
	0x43, 0x16, 0xe8, 0xcd, 0x29, 0x0b, 0xf4, 0x67, 0x15, 0xbb, 0x75, 0xda, 0xa4, 0xf3, 0x8f, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x63, 0x95, 0xc5, 0xfa, 0xde, 0x0e, 0x00, 0x00,
}
